theory TrafficLights imports "../VCTheory"
begin

abbreviation requestButton' :: variable where "requestButton' \<equiv> (Suc 0)"
abbreviation trafficLight' :: variable where "trafficLight' \<equiv> (Suc (Suc 0))"
abbreviation requestButtonPressed' :: variable where "requestButtonPressed' \<equiv> (Suc (Suc (Suc 0)))"

abbreviation controller' :: process where "controller' \<equiv> (Suc 0)"

abbreviation controller'redAfterMinimalRed' :: pstate where "controller'redAfterMinimalRed' \<equiv> (Suc (Suc (Suc 0)))"
abbreviation controller'green' :: pstate where "controller'green' \<equiv> (Suc (Suc (Suc (Suc (Suc 0)))))"
abbreviation controller'redToGreen' :: pstate where "controller'redToGreen' \<equiv> (Suc (Suc (Suc (Suc 0))))"
abbreviation controller'minimalRed' :: pstate where "controller'minimalRed' \<equiv> (Suc (Suc 0))"

abbreviation GREEN' :: bool where "GREEN' \<equiv> True"
abbreviation RED' :: bool where "RED' \<equiv> False"
abbreviation PRESSED' :: bool where "PRESSED' \<equiv> True"
abbreviation NOT_PRESSED' :: bool where "NOT_PRESSED' \<equiv> False"
abbreviation MINIMAL_RED_TIME_LIMIT' :: nat where "MINIMAL_RED_TIME_LIMIT' \<equiv> 10000"
abbreviation RED_TO_GREEN_TIME_LIMIT' :: nat where "RED_TO_GREEN_TIME_LIMIT' \<equiv> 5000"
abbreviation GREEN_TIME_LIMIT' :: nat where "GREEN_TIME_LIMIT' \<equiv> 30000"

abbreviation MINIMAL_RED_TIME_LIMIT'TIMEOUT :: nat where "MINIMAL_RED_TIME_LIMIT'TIMEOUT \<equiv> 100"
abbreviation RED_TO_GREEN_TIME_LIMIT'TIMEOUT :: nat where "RED_TO_GREEN_TIME_LIMIT'TIMEOUT \<equiv> 50"
abbreviation GREEN_TIME_LIMIT'TIMEOUT :: nat where "GREEN_TIME_LIMIT'TIMEOUT \<equiv> 300"

(*Verification conditions*)


definition VC1 where
  "VC1 inv0 s0 \<equiv>
  (
    (
      s0
    =
      (toEnv
        (setPstate
          emptyState
          controller'
          controller'minimalRed'
        )
      )
    )
  -->
    (inv0
      s0
    )
  )
  "

definition VC2 where
  "VC2 inv0 env s0 requestButton'value \<equiv>
  (
    (
      (
        (inv0
          s0
        )
      \<and>
        (env
          (setVarBool
            s0
            requestButton'
            requestButton'value
          )
        )
      )
    \<and>
      (
        (
          (
            (getPstate
              (setVarBool
                s0
                requestButton'
                requestButton'value
              )
              controller'
            )
          =
            controller'minimalRed'
          )
        \<and>
          (getVarBool
            (setVarBool
              s0
              requestButton'
              requestButton'value
            )
            requestButton'
          )
        )
      \<and>
        (
          MINIMAL_RED_TIME_LIMIT'TIMEOUT
        <=
          (ltime
            (setVarBool
              (setVarBool
                s0
                requestButton'
                requestButton'value
              )
              requestButtonPressed'
              True
            )
            controller'
          )
        )
      )
    )
  -->
    (inv0
      (toEnv
        (setPstate
          (setVarBool
            (setVarBool
              s0
              requestButton'
              requestButton'value
            )
            requestButtonPressed'
            True
          )
          controller'
          controller'redAfterMinimalRed'
        )
      )
    )
  )
  "

definition VC3 where
  "VC3 inv0 env s0 requestButton'value \<equiv>
  (
    (
      (
        (inv0
          s0
        )
      \<and>
        (env
          (setVarBool
            s0
            requestButton'
            requestButton'value
          )
        )
      )
    \<and>
      (
        (
          (
            (getPstate
              (setVarBool
                s0
                requestButton'
                requestButton'value
              )
              controller'
            )
          =
            controller'minimalRed'
          )
        \<and>
          (getVarBool
            (setVarBool
              s0
              requestButton'
              requestButton'value
            )
            requestButton'
          )
        )
      \<and>
        (\<not>
          (
            MINIMAL_RED_TIME_LIMIT'TIMEOUT
          <=
            (ltime
              (setVarBool
                (setVarBool
                  s0
                  requestButton'
                  requestButton'value
                )
                requestButtonPressed'
                True
              )
              controller'
            )
          )
        )
      )
    )
  -->
    (inv0
      (toEnv
        (setVarBool
          (setVarBool
            s0
            requestButton'
            requestButton'value
          )
          requestButtonPressed'
          True
        )
      )
    )
  )
  "

definition VC4 where
  "VC4 inv0 env s0 requestButton'value \<equiv>
  (
    (
      (
        (inv0
          s0
        )
      \<and>
        (env
          (setVarBool
            s0
            requestButton'
            requestButton'value
          )
        )
      )
    \<and>
      (
        (
          (
            (getPstate
              (setVarBool
                s0
                requestButton'
                requestButton'value
              )
              controller'
            )
          =
            controller'minimalRed'
          )
        \<and>
          (\<not>
            (getVarBool
              (setVarBool
                s0
                requestButton'
                requestButton'value
              )
              requestButton'
            )
          )
        )
      \<and>
        (
          MINIMAL_RED_TIME_LIMIT'TIMEOUT
        <=
          (ltime
            (setVarBool
              s0
              requestButton'
              requestButton'value
            )
            controller'
          )
        )
      )
    )
  -->
    (inv0
      (toEnv
        (setPstate
          (setVarBool
            s0
            requestButton'
            requestButton'value
          )
          controller'
          controller'redAfterMinimalRed'
        )
      )
    )
  )
  "

definition VC5 where
  "VC5 inv0 env s0 requestButton'value \<equiv>
  (
    (
      (
        (inv0
          s0
        )
      \<and>
        (env
          (setVarBool
            s0
            requestButton'
            requestButton'value
          )
        )
      )
    \<and>
      (
        (
          (
            (getPstate
              (setVarBool
                s0
                requestButton'
                requestButton'value
              )
              controller'
            )
          =
            controller'minimalRed'
          )
        \<and>
          (\<not>
            (getVarBool
              (setVarBool
                s0
                requestButton'
                requestButton'value
              )
              requestButton'
            )
          )
        )
      \<and>
        (\<not>
          (
            MINIMAL_RED_TIME_LIMIT'TIMEOUT
          <=
            (ltime
              (setVarBool
                s0
                requestButton'
                requestButton'value
              )
              controller'
            )
          )
        )
      )
    )
  -->
    (inv0
      (toEnv
        (setVarBool
          s0
          requestButton'
          requestButton'value
        )
      )
    )
  )
  "

definition VC6 where
  "VC6 inv0 env s0 requestButton'value \<equiv>
  (
    (
      (
        (inv0
          s0
        )
      \<and>
        (env
          (setVarBool
            s0
            requestButton'
            requestButton'value
          )
        )
      )
    \<and>
      (
        (
          (getPstate
            (setVarBool
              s0
              requestButton'
              requestButton'value
            )
            controller'
          )
        =
          controller'redAfterMinimalRed'
        )
      \<and>
        (
          (getVarBool
            (setVarBool
              s0
              requestButton'
              requestButton'value
            )
            requestButtonPressed'
          )
        \<or>
          (getVarBool
            (setVarBool
              s0
              requestButton'
              requestButton'value
            )
            requestButton'
          )
        )
      )
    )
  -->
    (inv0
      (toEnv
        (setPstate
          (setVarBool
            s0
            requestButton'
            requestButton'value
          )
          controller'
          controller'redToGreen'
        )
      )
    )
  )
  "

definition VC7 where
  "VC7 inv0 env s0 requestButton'value \<equiv>
  (
    (
      (
        (inv0
          s0
        )
      \<and>
        (env
          (setVarBool
            s0
            requestButton'
            requestButton'value
          )
        )
      )
    \<and>
      (
        (
          (getPstate
            (setVarBool
              s0
              requestButton'
              requestButton'value
            )
            controller'
          )
        =
          controller'redAfterMinimalRed'
        )
      \<and>
        (\<not>
          (
            (getVarBool
              (setVarBool
                s0
                requestButton'
                requestButton'value
              )
              requestButtonPressed'
            )
          \<or>
            (getVarBool
              (setVarBool
                s0
                requestButton'
                requestButton'value
              )
              requestButton'
            )
          )
        )
      )
    )
  -->
    (inv0
      (toEnv
        (setVarBool
          s0
          requestButton'
          requestButton'value
        )
      )
    )
  )
  "

definition VC8 where
  "VC8 inv0 env s0 requestButton'value \<equiv>
  (
    (
      (
        (inv0
          s0
        )
      \<and>
        (env
          (setVarBool
            s0
            requestButton'
            requestButton'value
          )
        )
      )
    \<and>
      (
        (
          (getPstate
            (setVarBool
              s0
              requestButton'
              requestButton'value
            )
            controller'
          )
        =
          controller'redToGreen'
        )
      \<and>
        (
          RED_TO_GREEN_TIME_LIMIT'TIMEOUT
        <=
          (ltime
            (setVarBool
              s0
              requestButton'
              requestButton'value
            )
            controller'
          )
        )
      )
    )
  -->
    (inv0
      (toEnv
        (setPstate
          (setVarBool
            (setVarBool
              (setVarBool
                s0
                requestButton'
                requestButton'value
              )
              trafficLight'
              GREEN'
            )
            requestButtonPressed'
            False
          )
          controller'
          controller'green'
        )
      )
    )
  )
  "

definition VC9 where
  "VC9 inv0 env s0 requestButton'value \<equiv>
  (
    (
      (
        (inv0
          s0
        )
      \<and>
        (env
          (setVarBool
            s0
            requestButton'
            requestButton'value
          )
        )
      )
    \<and>
      (
        (
          (getPstate
            (setVarBool
              s0
              requestButton'
              requestButton'value
            )
            controller'
          )
        =
          controller'redToGreen'
        )
      \<and>
        (\<not>
          (
            RED_TO_GREEN_TIME_LIMIT'TIMEOUT
          <=
            (ltime
              (setVarBool
                s0
                requestButton'
                requestButton'value
              )
              controller'
            )
          )
        )
      )
    )
  -->
    (inv0
      (toEnv
        (setVarBool
          s0
          requestButton'
          requestButton'value
        )
      )
    )
  )
  "

definition VC10 where
  "VC10 inv0 env s0 requestButton'value \<equiv>
  (
    (
      (
        (inv0
          s0
        )
      \<and>
        (env
          (setVarBool
            s0
            requestButton'
            requestButton'value
          )
        )
      )
    \<and>
      (
        (
          (getPstate
            (setVarBool
              s0
              requestButton'
              requestButton'value
            )
            controller'
          )
        =
          controller'green'
        )
      \<and>
        (
          GREEN_TIME_LIMIT'TIMEOUT
        <=
          (ltime
            (setVarBool
              s0
              requestButton'
              requestButton'value
            )
            controller'
          )
        )
      )
    )
  -->
    (inv0
      (toEnv
        (setPstate
          (setVarBool
            (setVarBool
              s0
              requestButton'
              requestButton'value
            )
            trafficLight'
            RED'
          )
          controller'
          controller'minimalRed'
        )
      )
    )
  )
  "

definition VC11 where
  "VC11 inv0 env s0 requestButton'value \<equiv>
  (
    (
      (
        (inv0
          s0
        )
      \<and>
        (env
          (setVarBool
            s0
            requestButton'
            requestButton'value
          )
        )
      )
    \<and>
      (
        (
          (getPstate
            (setVarBool
              s0
              requestButton'
              requestButton'value
            )
            controller'
          )
        =
          controller'green'
        )
      \<and>
        (\<not>
          (
            GREEN_TIME_LIMIT'TIMEOUT
          <=
            (ltime
              (setVarBool
                s0
                requestButton'
                requestButton'value
              )
              controller'
            )
          )
        )
      )
    )
  -->
    (inv0
      (toEnv
        (setVarBool
          s0
          requestButton'
          requestButton'value
        )
      )
    )
  )
  "

definition VC12 where
  "VC12 inv0 env s0 requestButton'value \<equiv>
  (
    (
      (
        (inv0
          s0
        )
      \<and>
        (env
          (setVarBool
            s0
            requestButton'
            requestButton'value
          )
        )
      )
    \<and>
      (
        (getPstate
          (setVarBool
            s0
            requestButton'
            requestButton'value
          )
          controller'
        )
      =
        STOP
      )
    )
  -->
    (inv0
      (toEnv
        (setVarBool
          s0
          requestButton'
          requestButton'value
        )
      )
    )
  )
  "

definition VC13 where
  "VC13 inv0 env s0 requestButton'value \<equiv>
  (
    (
      (
        (inv0
          s0
        )
      \<and>
        (env
          (setVarBool
            s0
            requestButton'
            requestButton'value
          )
        )
      )
    \<and>
      (
        (getPstate
          (setVarBool
            s0
            requestButton'
            requestButton'value
          )
          controller'
        )
      =
        ERROR
      )
    )
  -->
    (inv0
      (toEnv
        (setVarBool
          s0
          requestButton'
          requestButton'value
        )
      )
    )
  )
  "
end
