/**
 * generated by Xtext 2.36.0
 */
package su.nsk.iae.rpl.rPL;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Add Term</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link su.nsk.iae.rpl.rPL.AddTerm#getAddOp <em>Add Op</em>}</li>
 * </ul>
 *
 * @see su.nsk.iae.rpl.rPL.RPLPackage#getAddTerm()
 * @model
 * @generated
 */
public interface AddTerm extends CompareTerm
{
  /**
   * Returns the value of the '<em><b>Add Op</b></em>' attribute.
   * The literals are from the enumeration {@link su.nsk.iae.rpl.rPL.AddOperator}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Add Op</em>' attribute.
   * @see su.nsk.iae.rpl.rPL.AddOperator
   * @see #setAddOp(AddOperator)
   * @see su.nsk.iae.rpl.rPL.RPLPackage#getAddTerm_AddOp()
   * @model
   * @generated
   */
  AddOperator getAddOp();

  /**
   * Sets the value of the '{@link su.nsk.iae.rpl.rPL.AddTerm#getAddOp <em>Add Op</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Add Op</em>' attribute.
   * @see su.nsk.iae.rpl.rPL.AddOperator
   * @see #getAddOp()
   * @generated
   */
  void setAddOp(AddOperator value);

} // AddTerm
