/**
 * generated by Xtext 2.36.0
 */
package su.nsk.iae.rpl.rPL;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Always Implication</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link su.nsk.iae.rpl.rPL.AlwaysImplication#getState <em>State</em>}</li>
 *   <li>{@link su.nsk.iae.rpl.rPL.AlwaysImplication#getLeft <em>Left</em>}</li>
 *   <li>{@link su.nsk.iae.rpl.rPL.AlwaysImplication#getRight <em>Right</em>}</li>
 * </ul>
 *
 * @see su.nsk.iae.rpl.rPL.RPLPackage#getAlwaysImplication()
 * @model
 * @generated
 */
public interface AlwaysImplication extends EObject
{
  /**
   * Returns the value of the '<em><b>State</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>State</em>' reference.
   * @see #setState(UpdateStateVariable)
   * @see su.nsk.iae.rpl.rPL.RPLPackage#getAlwaysImplication_State()
   * @model
   * @generated
   */
  UpdateStateVariable getState();

  /**
   * Sets the value of the '{@link su.nsk.iae.rpl.rPL.AlwaysImplication#getState <em>State</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>State</em>' reference.
   * @see #getState()
   * @generated
   */
  void setState(UpdateStateVariable value);

  /**
   * Returns the value of the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Left</em>' containment reference.
   * @see #setLeft(AtomicFormula)
   * @see su.nsk.iae.rpl.rPL.RPLPackage#getAlwaysImplication_Left()
   * @model containment="true"
   * @generated
   */
  AtomicFormula getLeft();

  /**
   * Sets the value of the '{@link su.nsk.iae.rpl.rPL.AlwaysImplication#getLeft <em>Left</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Left</em>' containment reference.
   * @see #getLeft()
   * @generated
   */
  void setLeft(AtomicFormula value);

  /**
   * Returns the value of the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Right</em>' containment reference.
   * @see #setRight(AtomicFormula)
   * @see su.nsk.iae.rpl.rPL.RPLPackage#getAlwaysImplication_Right()
   * @model containment="true"
   * @generated
   */
  AtomicFormula getRight();

  /**
   * Sets the value of the '{@link su.nsk.iae.rpl.rPL.AlwaysImplication#getRight <em>Right</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Right</em>' containment reference.
   * @see #getRight()
   * @generated
   */
  void setRight(AtomicFormula value);

} // AlwaysImplication
