/**
 * generated by Xtext 2.36.0
 */
package su.nsk.iae.rpl.rPL;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Always Implication Parameter Value</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link su.nsk.iae.rpl.rPL.AlwaysImplicationParameterValue#getState <em>State</em>}</li>
 *   <li>{@link su.nsk.iae.rpl.rPL.AlwaysImplicationParameterValue#getFormula <em>Formula</em>}</li>
 * </ul>
 *
 * @see su.nsk.iae.rpl.rPL.RPLPackage#getAlwaysImplicationParameterValue()
 * @model
 * @generated
 */
public interface AlwaysImplicationParameterValue extends EObject
{
  /**
   * Returns the value of the '<em><b>State</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>State</em>' containment reference.
   * @see #setState(UpdateStateVariable)
   * @see su.nsk.iae.rpl.rPL.RPLPackage#getAlwaysImplicationParameterValue_State()
   * @model containment="true"
   * @generated
   */
  UpdateStateVariable getState();

  /**
   * Sets the value of the '{@link su.nsk.iae.rpl.rPL.AlwaysImplicationParameterValue#getState <em>State</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>State</em>' containment reference.
   * @see #getState()
   * @generated
   */
  void setState(UpdateStateVariable value);

  /**
   * Returns the value of the '<em><b>Formula</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Formula</em>' containment reference.
   * @see #setFormula(NegationFormula)
   * @see su.nsk.iae.rpl.rPL.RPLPackage#getAlwaysImplicationParameterValue_Formula()
   * @model containment="true"
   * @generated
   */
  NegationFormula getFormula();

  /**
   * Sets the value of the '{@link su.nsk.iae.rpl.rPL.AlwaysImplicationParameterValue#getFormula <em>Formula</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Formula</em>' containment reference.
   * @see #getFormula()
   * @generated
   */
  void setFormula(NegationFormula value);

} // AlwaysImplicationParameterValue
