/**
 * generated by Xtext 2.36.0
 */
package su.nsk.iae.rpl.rPL;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Conjunction</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see su.nsk.iae.rpl.rPL.RPLPackage#getConjunction()
 * @model
 * @generated
 */
public interface Conjunction extends ConjunctionFormula
{
} // Conjunction
