/**
 * generated by Xtext 2.36.0
 */
package su.nsk.iae.rpl.rPL;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Disjunction Lemma Premise Formula</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see su.nsk.iae.rpl.rPL.RPLPackage#getDisjunctionLemmaPremiseFormula()
 * @model
 * @generated
 */
public interface DisjunctionLemmaPremiseFormula extends LemmaPremiseFormula
{
} // DisjunctionLemmaPremiseFormula
