/**
 * generated by Xtext 2.36.0
 */
package su.nsk.iae.rpl.rPL;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Extra Invariant</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link su.nsk.iae.rpl.rPL.ExtraInvariant#getName <em>Name</em>}</li>
 *   <li>{@link su.nsk.iae.rpl.rPL.ExtraInvariant#getPattern <em>Pattern</em>}</li>
 *   <li>{@link su.nsk.iae.rpl.rPL.ExtraInvariant#getReqName <em>Req Name</em>}</li>
 *   <li>{@link su.nsk.iae.rpl.rPL.ExtraInvariant#getReq <em>Req</em>}</li>
 * </ul>
 *
 * @see su.nsk.iae.rpl.rPL.RPLPackage#getExtraInvariant()
 * @model
 * @generated
 */
public interface ExtraInvariant extends Element
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see su.nsk.iae.rpl.rPL.RPLPackage#getExtraInvariant_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link su.nsk.iae.rpl.rPL.ExtraInvariant#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Pattern</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Pattern</em>' reference.
   * @see #setPattern(DerivedExtraInvariantPattern)
   * @see su.nsk.iae.rpl.rPL.RPLPackage#getExtraInvariant_Pattern()
   * @model
   * @generated
   */
  DerivedExtraInvariantPattern getPattern();

  /**
   * Sets the value of the '{@link su.nsk.iae.rpl.rPL.ExtraInvariant#getPattern <em>Pattern</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Pattern</em>' reference.
   * @see #getPattern()
   * @generated
   */
  void setPattern(DerivedExtraInvariantPattern value);

  /**
   * Returns the value of the '<em><b>Req Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Req Name</em>' attribute.
   * @see #setReqName(String)
   * @see su.nsk.iae.rpl.rPL.RPLPackage#getExtraInvariant_ReqName()
   * @model
   * @generated
   */
  String getReqName();

  /**
   * Sets the value of the '{@link su.nsk.iae.rpl.rPL.ExtraInvariant#getReqName <em>Req Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Req Name</em>' attribute.
   * @see #getReqName()
   * @generated
   */
  void setReqName(String value);

  /**
   * Returns the value of the '<em><b>Req</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Req</em>' reference.
   * @see #setReq(Requirement)
   * @see su.nsk.iae.rpl.rPL.RPLPackage#getExtraInvariant_Req()
   * @model
   * @generated
   */
  Requirement getReq();

  /**
   * Sets the value of the '{@link su.nsk.iae.rpl.rPL.ExtraInvariant#getReq <em>Req</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Req</em>' reference.
   * @see #getReq()
   * @generated
   */
  void setReq(Requirement value);

} // ExtraInvariant
