/**
 * generated by Xtext 2.36.0
 */
package su.nsk.iae.rpl.rPL;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Future Requirement Pattern</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link su.nsk.iae.rpl.rPL.FutureRequirementPattern#getName <em>Name</em>}</li>
 *   <li>{@link su.nsk.iae.rpl.rPL.FutureRequirementPattern#getCParams <em>CParams</em>}</li>
 *   <li>{@link su.nsk.iae.rpl.rPL.FutureRequirementPattern#getFmParams <em>Fm Params</em>}</li>
 *   <li>{@link su.nsk.iae.rpl.rPL.FutureRequirementPattern#getFile <em>File</em>}</li>
 *   <li>{@link su.nsk.iae.rpl.rPL.FutureRequirementPattern#getExtraInvPattern <em>Extra Inv Pattern</em>}</li>
 *   <li>{@link su.nsk.iae.rpl.rPL.FutureRequirementPattern#getLessas <em>Lessas</em>}</li>
 * </ul>
 *
 * @see su.nsk.iae.rpl.rPL.RPLPackage#getFutureRequirementPattern()
 * @model
 * @generated
 */
public interface FutureRequirementPattern extends Element, RequirementPattern
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see su.nsk.iae.rpl.rPL.RPLPackage#getFutureRequirementPattern_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link su.nsk.iae.rpl.rPL.FutureRequirementPattern#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>CParams</b></em>' containment reference list.
   * The list contents are of type {@link su.nsk.iae.rpl.rPL.ConstantParameter}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>CParams</em>' containment reference list.
   * @see su.nsk.iae.rpl.rPL.RPLPackage#getFutureRequirementPattern_CParams()
   * @model containment="true"
   * @generated
   */
  EList<ConstantParameter> getCParams();

  /**
   * Returns the value of the '<em><b>Fm Params</b></em>' containment reference list.
   * The list contents are of type {@link su.nsk.iae.rpl.rPL.FormulaParameter}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Fm Params</em>' containment reference list.
   * @see su.nsk.iae.rpl.rPL.RPLPackage#getFutureRequirementPattern_FmParams()
   * @model containment="true"
   * @generated
   */
  EList<FormulaParameter> getFmParams();

  /**
   * Returns the value of the '<em><b>File</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>File</em>' attribute.
   * @see #setFile(String)
   * @see su.nsk.iae.rpl.rPL.RPLPackage#getFutureRequirementPattern_File()
   * @model
   * @generated
   */
  String getFile();

  /**
   * Sets the value of the '{@link su.nsk.iae.rpl.rPL.FutureRequirementPattern#getFile <em>File</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>File</em>' attribute.
   * @see #getFile()
   * @generated
   */
  void setFile(String value);

  /**
   * Returns the value of the '<em><b>Extra Inv Pattern</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Extra Inv Pattern</em>' reference.
   * @see #setExtraInvPattern(FutureExtraInvariantPattern)
   * @see su.nsk.iae.rpl.rPL.RPLPackage#getFutureRequirementPattern_ExtraInvPattern()
   * @model
   * @generated
   */
  FutureExtraInvariantPattern getExtraInvPattern();

  /**
   * Sets the value of the '{@link su.nsk.iae.rpl.rPL.FutureRequirementPattern#getExtraInvPattern <em>Extra Inv Pattern</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Extra Inv Pattern</em>' reference.
   * @see #getExtraInvPattern()
   * @generated
   */
  void setExtraInvPattern(FutureExtraInvariantPattern value);

  /**
   * Returns the value of the '<em><b>Lessas</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Lessas</em>' containment reference.
   * @see #setLessas(FutureLemmas)
   * @see su.nsk.iae.rpl.rPL.RPLPackage#getFutureRequirementPattern_Lessas()
   * @model containment="true"
   * @generated
   */
  FutureLemmas getLessas();

  /**
   * Sets the value of the '{@link su.nsk.iae.rpl.rPL.FutureRequirementPattern#getLessas <em>Lessas</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Lessas</em>' containment reference.
   * @see #getLessas()
   * @generated
   */
  void setLessas(FutureLemmas value);

} // FutureRequirementPattern
