/**
 * generated by Xtext 2.36.0
 */
package su.nsk.iae.rpl.rPL;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Future Extra Invariant Pattern</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link su.nsk.iae.rpl.rPL.FutureExtraInvariantPattern#getName <em>Name</em>}</li>
 *   <li>{@link su.nsk.iae.rpl.rPL.FutureExtraInvariantPattern#getCParams <em>CParams</em>}</li>
 *   <li>{@link su.nsk.iae.rpl.rPL.FutureExtraInvariantPattern#getFnParams <em>Fn Params</em>}</li>
 *   <li>{@link su.nsk.iae.rpl.rPL.FutureExtraInvariantPattern#getFmParams <em>Fm Params</em>}</li>
 *   <li>{@link su.nsk.iae.rpl.rPL.FutureExtraInvariantPattern#getFile <em>File</em>}</li>
 *   <li>{@link su.nsk.iae.rpl.rPL.FutureExtraInvariantPattern#getLemmas <em>Lemmas</em>}</li>
 * </ul>
 *
 * @see su.nsk.iae.rpl.rPL.RPLPackage#getFutureExtraInvariantPattern()
 * @model
 * @generated
 */
public interface FutureExtraInvariantPattern extends Element
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see su.nsk.iae.rpl.rPL.RPLPackage#getFutureExtraInvariantPattern_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link su.nsk.iae.rpl.rPL.FutureExtraInvariantPattern#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>CParams</b></em>' containment reference list.
   * The list contents are of type {@link su.nsk.iae.rpl.rPL.ConstantParameter}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>CParams</em>' containment reference list.
   * @see su.nsk.iae.rpl.rPL.RPLPackage#getFutureExtraInvariantPattern_CParams()
   * @model containment="true"
   * @generated
   */
  EList<ConstantParameter> getCParams();

  /**
   * Returns the value of the '<em><b>Fn Params</b></em>' containment reference list.
   * The list contents are of type {@link su.nsk.iae.rpl.rPL.FunctionalParameter}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Fn Params</em>' containment reference list.
   * @see su.nsk.iae.rpl.rPL.RPLPackage#getFutureExtraInvariantPattern_FnParams()
   * @model containment="true"
   * @generated
   */
  EList<FunctionalParameter> getFnParams();

  /**
   * Returns the value of the '<em><b>Fm Params</b></em>' containment reference list.
   * The list contents are of type {@link su.nsk.iae.rpl.rPL.RegularFormulaParameter}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Fm Params</em>' containment reference list.
   * @see su.nsk.iae.rpl.rPL.RPLPackage#getFutureExtraInvariantPattern_FmParams()
   * @model containment="true"
   * @generated
   */
  EList<RegularFormulaParameter> getFmParams();

  /**
   * Returns the value of the '<em><b>File</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>File</em>' attribute.
   * @see #setFile(String)
   * @see su.nsk.iae.rpl.rPL.RPLPackage#getFutureExtraInvariantPattern_File()
   * @model
   * @generated
   */
  String getFile();

  /**
   * Sets the value of the '{@link su.nsk.iae.rpl.rPL.FutureExtraInvariantPattern#getFile <em>File</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>File</em>' attribute.
   * @see #getFile()
   * @generated
   */
  void setFile(String value);

  /**
   * Returns the value of the '<em><b>Lemmas</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Lemmas</em>' containment reference.
   * @see #setLemmas(FutureLemmas)
   * @see su.nsk.iae.rpl.rPL.RPLPackage#getFutureExtraInvariantPattern_Lemmas()
   * @model containment="true"
   * @generated
   */
  FutureLemmas getLemmas();

  /**
   * Sets the value of the '{@link su.nsk.iae.rpl.rPL.FutureExtraInvariantPattern#getLemmas <em>Lemmas</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Lemmas</em>' containment reference.
   * @see #getLemmas()
   * @generated
   */
  void setLemmas(FutureLemmas value);

} // FutureExtraInvariantPattern
