/**
 * generated by Xtext 2.36.0
 */
package su.nsk.iae.rpl.rPL;

import org.eclipse.emf.ecore.EObject;

import su.nsk.iae.rpl.invpatterngenerator.ExtraInvariantPatternGenerator;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Inner Formula</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link su.nsk.iae.rpl.rPL.InnerFormula#getLeft <em>Left</em>}</li>
 *   <li>{@link su.nsk.iae.rpl.rPL.InnerFormula#getRight <em>Right</em>}</li>
 * </ul>
 *
 * @see su.nsk.iae.rpl.rPL.RPLPackage#getInnerFormula()
 * @model
 * @generated
 */
public interface InnerFormula extends EObject
{
	public su.nsk.iae.rpl.invpatterngenerator.Formula generateFormula(
			ExtraInvariantPatternGenerator generator);
	
  /**
   * Returns the value of the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Left</em>' containment reference.
   * @see #setLeft(InnerFormula)
   * @see su.nsk.iae.rpl.rPL.RPLPackage#getInnerFormula_Left()
   * @model containment="true"
   * @generated
   */
  InnerFormula getLeft();

  /**
   * Sets the value of the '{@link su.nsk.iae.rpl.rPL.InnerFormula#getLeft <em>Left</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Left</em>' containment reference.
   * @see #getLeft()
   * @generated
   */
  void setLeft(InnerFormula value);

  /**
   * Returns the value of the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Right</em>' containment reference.
   * @see #setRight(InnerFormula)
   * @see su.nsk.iae.rpl.rPL.RPLPackage#getInnerFormula_Right()
   * @model containment="true"
   * @generated
   */
  InnerFormula getRight();

  /**
   * Sets the value of the '{@link su.nsk.iae.rpl.rPL.InnerFormula#getRight <em>Right</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Right</em>' containment reference.
   * @see #getRight()
   * @generated
   */
  void setRight(InnerFormula value);

} // InnerFormula
