/**
 * generated by Xtext 2.36.0
 */
package su.nsk.iae.rpl.rPL;

import org.eclipse.emf.ecore.EObject;

import su.nsk.iae.rpl.invpatterngenerator.*;
import su.nsk.iae.rpl.invpatterngenerator.LemmaPremise;
import su.nsk.iae.rpl.invpatterngenerator.LemmaPremise;
import su.nsk.iae.rpl.invpatterngenerator.ParameterValueMap;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Lemma Premise Formula</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link su.nsk.iae.rpl.rPL.LemmaPremiseFormula#getLeft <em>Left</em>}</li>
 *   <li>{@link su.nsk.iae.rpl.rPL.LemmaPremiseFormula#getRight <em>Right</em>}</li>
 * </ul>
 *
 * @see su.nsk.iae.rpl.rPL.RPLPackage#getLemmaPremiseFormula()
 * @model
 * @generated
 */
public interface LemmaPremiseFormula extends EObject
{
	public LemmaPremise substitiuteParams(LemmaPremiseInstanceCreator instCreator, DerivedLemmaScheme scheme,  ParameterValueMap params);
  /**
   * Returns the value of the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Left</em>' containment reference.
   * @see #setLeft(EObject)
   * @see su.nsk.iae.rpl.rPL.RPLPackage#getLemmaPremiseFormula_Left()
   * @model containment="true"
   * @generated
   */
  EObject getLeft();

  /**
   * Sets the value of the '{@link su.nsk.iae.rpl.rPL.LemmaPremiseFormula#getLeft <em>Left</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Left</em>' containment reference.
   * @see #getLeft()
   * @generated
   */
  void setLeft(EObject value);

  /**
   * Returns the value of the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Right</em>' containment reference.
   * @see #setRight(LemmaPremiseFormula)
   * @see su.nsk.iae.rpl.rPL.RPLPackage#getLemmaPremiseFormula_Right()
   * @model containment="true"
   * @generated
   */
  LemmaPremiseFormula getRight();

  /**
   * Sets the value of the '{@link su.nsk.iae.rpl.rPL.LemmaPremiseFormula#getRight <em>Right</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Right</em>' containment reference.
   * @see #getRight()
   * @generated
   */
  void setRight(LemmaPremiseFormula value);

} // LemmaPremiseFormula
