/**
 * generated by Xtext 2.36.0
 */
package su.nsk.iae.rpl.rPL;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Mul Term</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link su.nsk.iae.rpl.rPL.MulTerm#getMulOp <em>Mul Op</em>}</li>
 * </ul>
 *
 * @see su.nsk.iae.rpl.rPL.RPLPackage#getMulTerm()
 * @model
 * @generated
 */
public interface MulTerm extends AddTerm
{
  /**
   * Returns the value of the '<em><b>Mul Op</b></em>' attribute.
   * The literals are from the enumeration {@link su.nsk.iae.rpl.rPL.MulOperator}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Mul Op</em>' attribute.
   * @see su.nsk.iae.rpl.rPL.MulOperator
   * @see #setMulOp(MulOperator)
   * @see su.nsk.iae.rpl.rPL.RPLPackage#getMulTerm_MulOp()
   * @model
   * @generated
   */
  MulOperator getMulOp();

  /**
   * Sets the value of the '{@link su.nsk.iae.rpl.rPL.MulTerm#getMulOp <em>Mul Op</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Mul Op</em>' attribute.
   * @see su.nsk.iae.rpl.rPL.MulOperator
   * @see #getMulOp()
   * @generated
   */
  void setMulOp(MulOperator value);

} // MulTerm
