/**
 * generated by Xtext 2.36.0
 */
package su.nsk.iae.rpl.rPL;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Numeric Literal</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link su.nsk.iae.rpl.rPL.NumericLiteral#isSig <em>Sig</em>}</li>
 *   <li>{@link su.nsk.iae.rpl.rPL.NumericLiteral#getValue <em>Value</em>}</li>
 * </ul>
 *
 * @see su.nsk.iae.rpl.rPL.RPLPackage#getNumericLiteral()
 * @model
 * @generated
 */
public interface NumericLiteral extends EObject
{
  /**
   * Returns the value of the '<em><b>Sig</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Sig</em>' attribute.
   * @see #setSig(boolean)
   * @see su.nsk.iae.rpl.rPL.RPLPackage#getNumericLiteral_Sig()
   * @model
   * @generated
   */
  boolean isSig();

  /**
   * Sets the value of the '{@link su.nsk.iae.rpl.rPL.NumericLiteral#isSig <em>Sig</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Sig</em>' attribute.
   * @see #isSig()
   * @generated
   */
  void setSig(boolean value);

  /**
   * Returns the value of the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Value</em>' attribute.
   * @see #setValue(String)
   * @see su.nsk.iae.rpl.rPL.RPLPackage#getNumericLiteral_Value()
   * @model
   * @generated
   */
  String getValue();

  /**
   * Sets the value of the '{@link su.nsk.iae.rpl.rPL.NumericLiteral#getValue <em>Value</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Value</em>' attribute.
   * @see #getValue()
   * @generated
   */
  void setValue(String value);

} // NumericLiteral
