/**
 * generated by Xtext 2.36.0
 */
package su.nsk.iae.rpl.rPL;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Outer Requirement Pattern Instance</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link su.nsk.iae.rpl.rPL.OuterRequirementPatternInstance#getPattern <em>Pattern</em>}</li>
 *   <li>{@link su.nsk.iae.rpl.rPL.OuterRequirementPatternInstance#getCParams <em>CParams</em>}</li>
 *   <li>{@link su.nsk.iae.rpl.rPL.OuterRequirementPatternInstance#getSimpleFmParams <em>Simple Fm Params</em>}</li>
 *   <li>{@link su.nsk.iae.rpl.rPL.OuterRequirementPatternInstance#getFmParams <em>Fm Params</em>}</li>
 * </ul>
 *
 * @see su.nsk.iae.rpl.rPL.RPLPackage#getOuterRequirementPatternInstance()
 * @model
 * @generated
 */
public interface OuterRequirementPatternInstance extends EObject
{
  /**
   * Returns the value of the '<em><b>Pattern</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Pattern</em>' reference.
   * @see #setPattern(OuterRequirementPattern)
   * @see su.nsk.iae.rpl.rPL.RPLPackage#getOuterRequirementPatternInstance_Pattern()
   * @model
   * @generated
   */
  OuterRequirementPattern getPattern();

  /**
   * Sets the value of the '{@link su.nsk.iae.rpl.rPL.OuterRequirementPatternInstance#getPattern <em>Pattern</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Pattern</em>' reference.
   * @see #getPattern()
   * @generated
   */
  void setPattern(OuterRequirementPattern value);

  /**
   * Returns the value of the '<em><b>CParams</b></em>' containment reference list.
   * The list contents are of type {@link su.nsk.iae.rpl.rPL.Term}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>CParams</em>' containment reference list.
   * @see su.nsk.iae.rpl.rPL.RPLPackage#getOuterRequirementPatternInstance_CParams()
   * @model containment="true"
   * @generated
   */
  EList<Term> getCParams();

  /**
   * Returns the value of the '<em><b>Simple Fm Params</b></em>' containment reference list.
   * The list contents are of type {@link su.nsk.iae.rpl.rPL.PatternFreeFormulaParameterValue}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Simple Fm Params</em>' containment reference list.
   * @see su.nsk.iae.rpl.rPL.RPLPackage#getOuterRequirementPatternInstance_SimpleFmParams()
   * @model containment="true"
   * @generated
   */
  EList<PatternFreeFormulaParameterValue> getSimpleFmParams();

  /**
   * Returns the value of the '<em><b>Fm Params</b></em>' containment reference list.
   * The list contents are of type {@link su.nsk.iae.rpl.rPL.FormulaParameterValue}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Fm Params</em>' containment reference list.
   * @see su.nsk.iae.rpl.rPL.RPLPackage#getOuterRequirementPatternInstance_FmParams()
   * @model containment="true"
   * @generated
   */
  EList<FormulaParameterValue> getFmParams();

} // OuterRequirementPatternInstance
