/**
 * generated by Xtext 2.36.0
 */
package su.nsk.iae.rpl.rPL;

import org.eclipse.emf.ecore.EObject;

import su.nsk.iae.rpl.invpatterngenerator.InnerFormulaGenerator;
import su.nsk.iae.rpl.invpatterngenerator.PatternFreeInnerFormula;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Pattern Free Formula</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link su.nsk.iae.rpl.rPL.PatternFreeFormula#getLeft <em>Left</em>}</li>
 *   <li>{@link su.nsk.iae.rpl.rPL.PatternFreeFormula#getRight <em>Right</em>}</li>
 * </ul>
 *
 * @see su.nsk.iae.rpl.rPL.RPLPackage#getPatternFreeFormula()
 * @model
 * @generated
 */
public interface PatternFreeFormula extends EObject
{
  /**
   * Returns the value of the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Left</em>' containment reference.
   * @see #setLeft(PatternFreeFormula)
   * @see su.nsk.iae.rpl.rPL.RPLPackage#getPatternFreeFormula_Left()
   * @model containment="true"
   * @generated
   */
  PatternFreeFormula getLeft();

  /**
   * Sets the value of the '{@link su.nsk.iae.rpl.rPL.PatternFreeFormula#getLeft <em>Left</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Left</em>' containment reference.
   * @see #getLeft()
   * @generated
   */
  void setLeft(PatternFreeFormula value);

  /**
   * Returns the value of the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Right</em>' containment reference.
   * @see #setRight(PatternFreeFormula)
   * @see su.nsk.iae.rpl.rPL.RPLPackage#getPatternFreeFormula_Right()
   * @model containment="true"
   * @generated
   */
  PatternFreeFormula getRight();

  /**
   * Sets the value of the '{@link su.nsk.iae.rpl.rPL.PatternFreeFormula#getRight <em>Right</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Right</em>' containment reference.
   * @see #getRight()
   * @generated
   */
  void setRight(PatternFreeFormula value);

PatternFreeInnerFormula generateFormula(InnerFormulaGenerator<?> innerFormulaGenerator);

} // PatternFreeFormula
