/**
 * generated by Xtext 2.36.0
 */
package su.nsk.iae.rpl.rPL;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Power Term</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see su.nsk.iae.rpl.rPL.RPLPackage#getPowerTerm()
 * @model
 * @generated
 */
public interface PowerTerm extends MulTerm
{
} // PowerTerm
