/**
 * generated by Xtext 2.36.0
 */
package su.nsk.iae.rpl.rPL;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Primary Inner Formula</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link su.nsk.iae.rpl.rPL.PrimaryInnerFormula#getAtomic <em>Atomic</em>}</li>
 *   <li>{@link su.nsk.iae.rpl.rPL.PrimaryInnerFormula#getPatternInst <em>Pattern Inst</em>}</li>
 *   <li>{@link su.nsk.iae.rpl.rPL.PrimaryInnerFormula#getNestedFormula <em>Nested Formula</em>}</li>
 * </ul>
 *
 * @see su.nsk.iae.rpl.rPL.RPLPackage#getPrimaryInnerFormula()
 * @model
 * @generated
 */
public interface PrimaryInnerFormula extends ConjunctionInnerFormula
{
  /**
   * Returns the value of the '<em><b>Atomic</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Atomic</em>' containment reference.
   * @see #setAtomic(NegationFormula)
   * @see su.nsk.iae.rpl.rPL.RPLPackage#getPrimaryInnerFormula_Atomic()
   * @model containment="true"
   * @generated
   */
  NegationFormula getAtomic();

  /**
   * Sets the value of the '{@link su.nsk.iae.rpl.rPL.PrimaryInnerFormula#getAtomic <em>Atomic</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Atomic</em>' containment reference.
   * @see #getAtomic()
   * @generated
   */
  void setAtomic(NegationFormula value);

  /**
   * Returns the value of the '<em><b>Pattern Inst</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Pattern Inst</em>' containment reference.
   * @see #setPatternInst(RequirementPatternInstance)
   * @see su.nsk.iae.rpl.rPL.RPLPackage#getPrimaryInnerFormula_PatternInst()
   * @model containment="true"
   * @generated
   */
  RequirementPatternInstance getPatternInst();

  /**
   * Sets the value of the '{@link su.nsk.iae.rpl.rPL.PrimaryInnerFormula#getPatternInst <em>Pattern Inst</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Pattern Inst</em>' containment reference.
   * @see #getPatternInst()
   * @generated
   */
  void setPatternInst(RequirementPatternInstance value);

  /**
   * Returns the value of the '<em><b>Nested Formula</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Nested Formula</em>' containment reference.
   * @see #setNestedFormula(InnerFormula)
   * @see su.nsk.iae.rpl.rPL.RPLPackage#getPrimaryInnerFormula_NestedFormula()
   * @model containment="true"
   * @generated
   */
  InnerFormula getNestedFormula();

  /**
   * Sets the value of the '{@link su.nsk.iae.rpl.rPL.PrimaryInnerFormula#getNestedFormula <em>Nested Formula</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Nested Formula</em>' containment reference.
   * @see #getNestedFormula()
   * @generated
   */
  void setNestedFormula(InnerFormula value);

} // PrimaryInnerFormula
