/**
 * generated by Xtext 2.36.0
 */
package su.nsk.iae.rpl.rPL;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Requirement Pattern Instance</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link su.nsk.iae.rpl.rPL.RequirementPatternInstance#getPattern <em>Pattern</em>}</li>
 *   <li>{@link su.nsk.iae.rpl.rPL.RequirementPatternInstance#getCParams <em>CParams</em>}</li>
 *   <li>{@link su.nsk.iae.rpl.rPL.RequirementPatternInstance#getFmParams <em>Fm Params</em>}</li>
 *   <li>{@link su.nsk.iae.rpl.rPL.RequirementPatternInstance#getFinState <em>Fin State</em>}</li>
 *   <li>{@link su.nsk.iae.rpl.rPL.RequirementPatternInstance#getCurState <em>Cur State</em>}</li>
 * </ul>
 *
 * @see su.nsk.iae.rpl.rPL.RPLPackage#getRequirementPatternInstance()
 * @model
 * @generated
 */
public interface RequirementPatternInstance extends EObject
{
  /**
   * Returns the value of the '<em><b>Pattern</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Pattern</em>' reference.
   * @see #setPattern(RequirementPattern)
   * @see su.nsk.iae.rpl.rPL.RPLPackage#getRequirementPatternInstance_Pattern()
   * @model
   * @generated
   */
  RequirementPattern getPattern();

  /**
   * Sets the value of the '{@link su.nsk.iae.rpl.rPL.RequirementPatternInstance#getPattern <em>Pattern</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Pattern</em>' reference.
   * @see #getPattern()
   * @generated
   */
  void setPattern(RequirementPattern value);

  /**
   * Returns the value of the '<em><b>CParams</b></em>' containment reference list.
   * The list contents are of type {@link su.nsk.iae.rpl.rPL.Term}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>CParams</em>' containment reference list.
   * @see su.nsk.iae.rpl.rPL.RPLPackage#getRequirementPatternInstance_CParams()
   * @model containment="true"
   * @generated
   */
  EList<Term> getCParams();

  /**
   * Returns the value of the '<em><b>Fm Params</b></em>' containment reference list.
   * The list contents are of type {@link su.nsk.iae.rpl.rPL.FormulaParameterValue}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Fm Params</em>' containment reference list.
   * @see su.nsk.iae.rpl.rPL.RPLPackage#getRequirementPatternInstance_FmParams()
   * @model containment="true"
   * @generated
   */
  EList<FormulaParameterValue> getFmParams();

  /**
   * Returns the value of the '<em><b>Fin State</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Fin State</em>' reference.
   * @see #setFinState(UpdateStateVariable)
   * @see su.nsk.iae.rpl.rPL.RPLPackage#getRequirementPatternInstance_FinState()
   * @model
   * @generated
   */
  UpdateStateVariable getFinState();

  /**
   * Sets the value of the '{@link su.nsk.iae.rpl.rPL.RequirementPatternInstance#getFinState <em>Fin State</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Fin State</em>' reference.
   * @see #getFinState()
   * @generated
   */
  void setFinState(UpdateStateVariable value);

  /**
   * Returns the value of the '<em><b>Cur State</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Cur State</em>' reference.
   * @see #setCurState(UpdateStateVariable)
   * @see su.nsk.iae.rpl.rPL.RPLPackage#getRequirementPatternInstance_CurState()
   * @model
   * @generated
   */
  UpdateStateVariable getCurState();

  /**
   * Sets the value of the '{@link su.nsk.iae.rpl.rPL.RequirementPatternInstance#getCurState <em>Cur State</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Cur State</em>' reference.
   * @see #getCurState()
   * @generated
   */
  void setCurState(UpdateStateVariable value);

} // RequirementPatternInstance
