/**
 * generated by Xtext 2.36.0
 */
package su.nsk.iae.rpl.rPL;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Simple Formula Parameter</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link su.nsk.iae.rpl.rPL.SimpleFormulaParameter#getName <em>Name</em>}</li>
 *   <li>{@link su.nsk.iae.rpl.rPL.SimpleFormulaParameter#getArity <em>Arity</em>}</li>
 * </ul>
 *
 * @see su.nsk.iae.rpl.rPL.RPLPackage#getSimpleFormulaParameter()
 * @model
 * @generated
 */
public interface SimpleFormulaParameter extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see su.nsk.iae.rpl.rPL.RPLPackage#getSimpleFormulaParameter_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link su.nsk.iae.rpl.rPL.SimpleFormulaParameter#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Arity</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Arity</em>' attribute.
   * @see #setArity(String)
   * @see su.nsk.iae.rpl.rPL.RPLPackage#getSimpleFormulaParameter_Arity()
   * @model
   * @generated
   */
  String getArity();

  /**
   * Sets the value of the '{@link su.nsk.iae.rpl.rPL.SimpleFormulaParameter#getArity <em>Arity</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Arity</em>' attribute.
   * @see #getArity()
   * @generated
   */
  void setArity(String value);

} // SimpleFormulaParameter
