/*
 * generated by Xtext 2.36.0
 */
package su.nsk.iae.rpl;

import org.eclipse.xtext.scoping.IGlobalScopeProvider;
import org.eclipse.xtext.scoping.impl.ImportUriGlobalScopeProvider;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class RPLRuntimeModule extends AbstractRPLRuntimeModule {
	@Override
	public Class<? extends IGlobalScopeProvider> bindIGlobalScopeProvider() {
		 return ImportUriGlobalScopeProvider.class;
	 }
}
