/*
 * generated by Xtext 2.36.0
 */
package su.nsk.iae.rpl;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class RPLStandaloneSetup extends RPLStandaloneSetupGenerated {

	public static void doSetup() {
		new RPLStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
