/*
 * generated by Xtext 2.36.0
 */
package su.nsk.iae.rpl.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractRPLScopeProvider extends DelegatingScopeProvider {
}
