theory BottleFilling_31001_32000 imports BottleFilling
begin
definition VC31794 where
  "VC31794 inv0 env s0 v_iLowLevel'value v_iHighLevel'value v_iLowTemp'value v_iHighTemp'value v_iBottleLevel'value v_iBottlePosition'value \<equiv>
  (
    (
      (
        (inv0
          s0
        )
      \<and>
        (env
          (setVarBool
            (setVarBool
              (setVarBool
                (setVarBool
                  (setVarBool
                    (setVarBool
                      s0
                      v_iLowLevel'
                      v_iLowLevel'value
                    )
                    v_iHighLevel'
                    v_iHighLevel'value
                  )
                  v_iLowTemp'
                  v_iLowTemp'value
                )
                v_iHighTemp'
                v_iHighTemp'value
              )
              v_iBottleLevel'
              v_iBottleLevel'value
            )
            v_iBottlePosition'
            v_iBottlePosition'value
          )
        )
      )
    \<and>
      (
        (
          (
            (
              (
                (
                  (
                    (
                      (getPstate
                        (setVarBool
                          (setVarBool
                            (setVarBool
                              (setVarBool
                                (setVarBool
                                  (setVarBool
                                    s0
                                    v_iLowLevel'
                                    v_iLowLevel'value
                                  )
                                  v_iHighLevel'
                                  v_iHighLevel'value
                                )
                                v_iLowTemp'
                                v_iLowTemp'value
                              )
                              v_iHighTemp'
                              v_iHighTemp'value
                            )
                            v_iBottleLevel'
                            v_iBottleLevel'value
                          )
                          v_iBottlePosition'
                          v_iBottlePosition'value
                        )
                        p_Initialization'
                      )
                    =
                      p_Initialization's_begin'
                    )
                  \<and>
                    (
                      (getPstate
                        (setPstate
                          (setPstate
                            (setVarBool
                              (setVarBool
                                (setVarBool
                                  (setVarBool
                                    (setVarBool
                                      (setVarBool
                                        s0
                                        v_iLowLevel'
                                        v_iLowLevel'value
                                      )
                                      v_iHighLevel'
                                      v_iHighLevel'value
                                    )
                                    v_iLowTemp'
                                    v_iLowTemp'value
                                  )
                                  v_iHighTemp'
                                  v_iHighTemp'value
                                )
                                v_iBottleLevel'
                                v_iBottleLevel'value
                              )
                              v_iBottlePosition'
                              v_iBottlePosition'value
                            )
                            p_TankFilling'
                            p_TankFilling's_begin'
                          )
                          p_Initialization'
                          p_Initialization's_waitForFilling'
                        )
                        p_MainLoop'
                      )
                    =
                      STOP
                    )
                  )
                \<and>
                  (
                    (getPstate
                      (setPstate
                        (setPstate
                          (setVarBool
                            (setVarBool
                              (setVarBool
                                (setVarBool
                                  (setVarBool
                                    (setVarBool
                                      s0
                                      v_iLowLevel'
                                      v_iLowLevel'value
                                    )
                                    v_iHighLevel'
                                    v_iHighLevel'value
                                  )
                                  v_iLowTemp'
                                  v_iLowTemp'value
                                )
                                v_iHighTemp'
                                v_iHighTemp'value
                              )
                              v_iBottleLevel'
                              v_iBottleLevel'value
                            )
                            v_iBottlePosition'
                            v_iBottlePosition'value
                          )
                          p_TankFilling'
                          p_TankFilling's_begin'
                        )
                        p_Initialization'
                        p_Initialization's_waitForFilling'
                      )
                      p_TankFilling'
                    )
                  =
                    p_TankFilling's_begin'
                  )
                )
              \<and>
                (
                  (getVarBool
                    (setPstate
                      (setPstate
                        (setVarBool
                          (setVarBool
                            (setVarBool
                              (setVarBool
                                (setVarBool
                                  (setVarBool
                                    s0
                                    v_iLowLevel'
                                    v_iLowLevel'value
                                  )
                                  v_iHighLevel'
                                  v_iHighLevel'value
                                )
                                v_iLowTemp'
                                v_iLowTemp'value
                              )
                              v_iHighTemp'
                              v_iHighTemp'value
                            )
                            v_iBottleLevel'
                            v_iBottleLevel'value
                          )
                          v_iBottlePosition'
                          v_iBottlePosition'value
                        )
                        p_TankFilling'
                        p_TankFilling's_begin'
                      )
                      p_Initialization'
                      p_Initialization's_waitForFilling'
                    )
                    v_iHighLevel'
                  )
                \<noteq>
                  True
                )
              )
            \<and>
              (
                (getPstate
                  (setPstate
                    (setVarBool
                      (setPstate
                        (setPstate
                          (setVarBool
                            (setVarBool
                              (setVarBool
                                (setVarBool
                                  (setVarBool
                                    (setVarBool
                                      s0
                                      v_iLowLevel'
                                      v_iLowLevel'value
                                    )
                                    v_iHighLevel'
                                    v_iHighLevel'value
                                  )
                                  v_iLowTemp'
                                  v_iLowTemp'value
                                )
                                v_iHighTemp'
                                v_iHighTemp'value
                              )
                              v_iBottleLevel'
                              v_iBottleLevel'value
                            )
                            v_iBottlePosition'
                            v_iBottlePosition'value
                          )
                          p_TankFilling'
                          p_TankFilling's_begin'
                        )
                        p_Initialization'
                        p_Initialization's_waitForFilling'
                      )
                      v_oFillTank'
                      True
                    )
                    p_TankFilling'
                    p_TankFilling's_tankFilled'
                  )
                  p_ForcedSterilization'
                )
              =
                STOP
              )
            )
          \<and>
            (
              (getPstate
                (setPstate
                  (setVarBool
                    (setPstate
                      (setPstate
                        (setVarBool
                          (setVarBool
                            (setVarBool
                              (setVarBool
                                (setVarBool
                                  (setVarBool
                                    s0
                                    v_iLowLevel'
                                    v_iLowLevel'value
                                  )
                                  v_iHighLevel'
                                  v_iHighLevel'value
                                )
                                v_iLowTemp'
                                v_iLowTemp'value
                              )
                              v_iHighTemp'
                              v_iHighTemp'value
                            )
                            v_iBottleLevel'
                            v_iBottleLevel'value
                          )
                          v_iBottlePosition'
                          v_iBottlePosition'value
                        )
                        p_TankFilling'
                        p_TankFilling's_begin'
                      )
                      p_Initialization'
                      p_Initialization's_waitForFilling'
                    )
                    v_oFillTank'
                    True
                  )
                  p_TankFilling'
                  p_TankFilling's_tankFilled'
                )
                p_KeepSterilization'
              )
            =
              STOP
            )
          )
        \<and>
          (
            (getPstate
              (setPstate
                (setVarBool
                  (setPstate
                    (setPstate
                      (setVarBool
                        (setVarBool
                          (setVarBool
                            (setVarBool
                              (setVarBool
                                (setVarBool
                                  s0
                                  v_iLowLevel'
                                  v_iLowLevel'value
                                )
                                v_iHighLevel'
                                v_iHighLevel'value
                              )
                              v_iLowTemp'
                              v_iLowTemp'value
                            )
                            v_iHighTemp'
                            v_iHighTemp'value
                          )
                          v_iBottleLevel'
                          v_iBottleLevel'value
                        )
                        v_iBottlePosition'
                        v_iBottlePosition'value
                      )
                      p_TankFilling'
                      p_TankFilling's_begin'
                    )
                    p_Initialization'
                    p_Initialization's_waitForFilling'
                  )
                  v_oFillTank'
                  True
                )
                p_TankFilling'
                p_TankFilling's_tankFilled'
              )
              p_BottleFilling'
            )
          =
            STOP
          )
        )
      \<and>
        (
          (getPstate
            (setPstate
              (setVarBool
                (setPstate
                  (setPstate
                    (setVarBool
                      (setVarBool
                        (setVarBool
                          (setVarBool
                            (setVarBool
                              (setVarBool
                                s0
                                v_iLowLevel'
                                v_iLowLevel'value
                              )
                              v_iHighLevel'
                              v_iHighLevel'value
                            )
                            v_iLowTemp'
                            v_iLowTemp'value
                          )
                          v_iHighTemp'
                          v_iHighTemp'value
                        )
                        v_iBottleLevel'
                        v_iBottleLevel'value
                      )
                      v_iBottlePosition'
                      v_iBottlePosition'value
                    )
                    p_TankFilling'
                    p_TankFilling's_begin'
                  )
                  p_Initialization'
                  p_Initialization's_waitForFilling'
                )
                v_oFillTank'
                True
              )
              p_TankFilling'
              p_TankFilling's_tankFilled'
            )
            p_NextBottle'
          )
        =
          STOP
        )
      )
    )
  -->
    (inv0
      (toEnv
        (setPstate
          (setVarBool
            (setPstate
              (setPstate
                (setVarBool
                  (setVarBool
                    (setVarBool
                      (setVarBool
                        (setVarBool
                          (setVarBool
                            s0
                            v_iLowLevel'
                            v_iLowLevel'value
                          )
                          v_iHighLevel'
                          v_iHighLevel'value
                        )
                        v_iLowTemp'
                        v_iLowTemp'value
                      )
                      v_iHighTemp'
                      v_iHighTemp'value
                    )
                    v_iBottleLevel'
                    v_iBottleLevel'value
                  )
                  v_iBottlePosition'
                  v_iBottlePosition'value
                )
                p_TankFilling'
                p_TankFilling's_begin'
              )
              p_Initialization'
              p_Initialization's_waitForFilling'
            )
            v_oFillTank'
            True
          )
          p_TankFilling'
          p_TankFilling's_tankFilled'
        )
      )
    )
  )
  "

end