theory HandDryer imports "../VCTheory"
begin

abbreviation hands' :: variable where "hands' \<equiv> (Suc 0)"
abbreviation dryer' :: variable where "dryer' \<equiv> (Suc (Suc 0))"

abbreviation Ctrl' :: process where "Ctrl' \<equiv> (Suc 0)"

abbreviation Ctrl'waiting' :: pstate where "Ctrl'waiting' \<equiv> (Suc (Suc 0))"
abbreviation Ctrl'drying' :: pstate where "Ctrl'drying' \<equiv> (Suc (Suc (Suc 0)))"



(*Verification conditions*)


definition VC1 where
  "VC1 inv0 s0 \<equiv>
  (
    (
      s0
    =
      (toEnv
        (setPstate
          emptyState
          Ctrl'
          Ctrl'waiting'
        )
      )
    )
  -->
    (inv0
      s0
    )
  )
  "

definition VC2 where
  "VC2 inv0 env s0 hands'value \<equiv>
  (
    (
      (
        (inv0
          s0
        )
      \<and>
        (env
          (setVarBool
            s0
            hands'
            hands'value
          )
        )
      )
    \<and>
      (
        (
          (getPstate
            (setVarBool
              s0
              hands'
              hands'value
            )
            Ctrl'
          )
        =
          Ctrl'waiting'
        )
      \<and>
        (getVarBool
          (setVarBool
            s0
            hands'
            hands'value
          )
          hands'
        )
      )
    )
  -->
    (inv0
      (toEnv
        (setPstate
          (setVarBool
            (setVarBool
              s0
              hands'
              hands'value
            )
            dryer'
            True
          )
          Ctrl'
          Ctrl'drying'
        )
      )
    )
  )
  "

definition VC3 where
  "VC3 inv0 env s0 hands'value \<equiv>
  (
    (
      (
        (inv0
          s0
        )
      \<and>
        (env
          (setVarBool
            s0
            hands'
            hands'value
          )
        )
      )
    \<and>
      (
        (
          (getPstate
            (setVarBool
              s0
              hands'
              hands'value
            )
            Ctrl'
          )
        =
          Ctrl'waiting'
        )
      \<and>
        (\<not>
          (getVarBool
            (setVarBool
              s0
              hands'
              hands'value
            )
            hands'
          )
        )
      )
    )
  -->
    (inv0
      (toEnv
        (setVarBool
          (setVarBool
            s0
            hands'
            hands'value
          )
          dryer'
          False
        )
      )
    )
  )
  "

definition VC4 where
  "VC4 inv0 env s0 hands'value \<equiv>
  (
    (
      (
        (inv0
          s0
        )
      \<and>
        (env
          (setVarBool
            s0
            hands'
            hands'value
          )
        )
      )
    \<and>
      (
        (
          (
            (getPstate
              (setVarBool
                s0
                hands'
                hands'value
              )
              Ctrl'
            )
          =
            Ctrl'drying'
          )
        \<and>
          (getVarBool
            (setVarBool
              s0
              hands'
              hands'value
            )
            hands'
          )
        )
      \<and>
        (
          10
        <=
          (ltime
            (reset
              (setVarBool
                s0
                hands'
                hands'value
              )
              Ctrl'
            )
            Ctrl'
          )
        )
      )
    )
  -->
    (inv0
      (toEnv
        (setPstate
          (reset
            (setVarBool
              s0
              hands'
              hands'value
            )
            Ctrl'
          )
          Ctrl'
          Ctrl'waiting'
        )
      )
    )
  )
  "

definition VC5 where
  "VC5 inv0 env s0 hands'value \<equiv>
  (
    (
      (
        (inv0
          s0
        )
      \<and>
        (env
          (setVarBool
            s0
            hands'
            hands'value
          )
        )
      )
    \<and>
      (
        (
          (
            (getPstate
              (setVarBool
                s0
                hands'
                hands'value
              )
              Ctrl'
            )
          =
            Ctrl'drying'
          )
        \<and>
          (getVarBool
            (setVarBool
              s0
              hands'
              hands'value
            )
            hands'
          )
        )
      \<and>
        (\<not>
          (
            10
          <=
            (ltime
              (reset
                (setVarBool
                  s0
                  hands'
                  hands'value
                )
                Ctrl'
              )
              Ctrl'
            )
          )
        )
      )
    )
  -->
    (inv0
      (toEnv
        (reset
          (setVarBool
            s0
            hands'
            hands'value
          )
          Ctrl'
        )
      )
    )
  )
  "

definition VC6 where
  "VC6 inv0 env s0 hands'value \<equiv>
  (
    (
      (
        (inv0
          s0
        )
      \<and>
        (env
          (setVarBool
            s0
            hands'
            hands'value
          )
        )
      )
    \<and>
      (
        (
          (
            (getPstate
              (setVarBool
                s0
                hands'
                hands'value
              )
              Ctrl'
            )
          =
            Ctrl'drying'
          )
        \<and>
          (\<not>
            (getVarBool
              (setVarBool
                s0
                hands'
                hands'value
              )
              hands'
            )
          )
        )
      \<and>
        (
          10
        <=
          (ltime
            (setVarBool
              s0
              hands'
              hands'value
            )
            Ctrl'
          )
        )
      )
    )
  -->
    (inv0
      (toEnv
        (setPstate
          (setVarBool
            s0
            hands'
            hands'value
          )
          Ctrl'
          Ctrl'waiting'
        )
      )
    )
  )
  "

definition VC7 where
  "VC7 inv0 env s0 hands'value \<equiv>
  (
    (
      (
        (inv0
          s0
        )
      \<and>
        (env
          (setVarBool
            s0
            hands'
            hands'value
          )
        )
      )
    \<and>
      (
        (
          (
            (getPstate
              (setVarBool
                s0
                hands'
                hands'value
              )
              Ctrl'
            )
          =
            Ctrl'drying'
          )
        \<and>
          (\<not>
            (getVarBool
              (setVarBool
                s0
                hands'
                hands'value
              )
              hands'
            )
          )
        )
      \<and>
        (\<not>
          (
            10
          <=
            (ltime
              (setVarBool
                s0
                hands'
                hands'value
              )
              Ctrl'
            )
          )
        )
      )
    )
  -->
    (inv0
      (toEnv
        (setVarBool
          s0
          hands'
          hands'value
        )
      )
    )
  )
  "

definition VC8 where
  "VC8 inv0 env s0 hands'value \<equiv>
  (
    (
      (
        (inv0
          s0
        )
      \<and>
        (env
          (setVarBool
            s0
            hands'
            hands'value
          )
        )
      )
    \<and>
      (
        (getPstate
          (setVarBool
            s0
            hands'
            hands'value
          )
          Ctrl'
        )
      =
        STOP
      )
    )
  -->
    (inv0
      (toEnv
        (setVarBool
          s0
          hands'
          hands'value
        )
      )
    )
  )
  "

definition VC9 where
  "VC9 inv0 env s0 hands'value \<equiv>
  (
    (
      (
        (inv0
          s0
        )
      \<and>
        (env
          (setVarBool
            s0
            hands'
            hands'value
          )
        )
      )
    \<and>
      (
        (getPstate
          (setVarBool
            s0
            hands'
            hands'value
          )
          Ctrl'
        )
      =
        ERROR
      )
    )
  -->
    (inv0
      (toEnv
        (setVarBool
          s0
          hands'
          hands'value
        )
      )
    )
  )
  "
end
