/*
 * generated by Xtext 2.36.0
 */
package su.nsk.iae.rpl.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import su.nsk.iae.rpl.RPLRuntimeModule;
import su.nsk.iae.rpl.RPLStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class RPLIdeSetup extends RPLStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new RPLRuntimeModule(), new RPLIdeModule()));
	}
	
}
