theory RevolvingDoor imports "../VCTheory"
begin

abbreviation user' :: variable where "user' \<equiv> (Suc 0)"
abbreviation pressure' :: variable where "pressure' \<equiv> (Suc (Suc 0))"
abbreviation rotation' :: variable where "rotation' \<equiv> (Suc (Suc (Suc 0)))"
abbreviation brake' :: variable where "brake' \<equiv> (Suc (Suc (Suc (Suc 0))))"

abbreviation Controller' :: process where "Controller' \<equiv> (Suc 0)"

abbreviation Controller'rotating' :: pstate where "Controller'rotating' \<equiv> (Suc (Suc (Suc 0)))"
abbreviation Controller'motionless' :: pstate where "Controller'motionless' \<equiv> (Suc (Suc 0))"
abbreviation Controller'suspended' :: pstate where "Controller'suspended' \<equiv> (Suc (Suc (Suc (Suc 0))))"

abbreviation SUSPENSION_TIME' :: nat where "SUSPENSION_TIME' \<equiv> 1000"
abbreviation DELAY' :: nat where "DELAY' \<equiv> 1000"

abbreviation SUSPENSION_TIME'TIMEOUT :: nat where "SUSPENSION_TIME'TIMEOUT \<equiv> 10"
abbreviation DELAY'TIMEOUT :: nat where "DELAY'TIMEOUT \<equiv> 10"

(*Verification conditions*)


definition VC1 where
  "VC1 inv0 s0 \<equiv>
  (
    (
      s0
    =
      (toEnv
        (setPstate
          emptyState
          Controller'
          Controller'motionless'
        )
      )
    )
  -->
    (inv0
      s0
    )
  )
  "

definition VC2 where
  "VC2 inv0 env s0 user'value pressure'value \<equiv>
  (
    (
      (
        (inv0
          s0
        )
      \<and>
        (env
          (setVarBool
            (setVarBool
              s0
              user'
              user'value
            )
            pressure'
            pressure'value
          )
        )
      )
    \<and>
      (
        (
          (
            (getPstate
              (setVarBool
                (setVarBool
                  s0
                  user'
                  user'value
                )
                pressure'
                pressure'value
              )
              Controller'
            )
          =
            Controller'motionless'
          )
        \<and>
          (getVarBool
            (setVarBool
              (setVarBool
                s0
                user'
                user'value
              )
              pressure'
              pressure'value
            )
            user'
          )
        )
      \<and>
        (getVarBool
          (setVarBool
            (setVarBool
              s0
              user'
              user'value
            )
            pressure'
            pressure'value
          )
          pressure'
        )
      )
    )
  -->
    (inv0
      (toEnv
        (setPstate
          (setVarBool
            (setVarBool
              (setVarBool
                s0
                user'
                user'value
              )
              pressure'
              pressure'value
            )
            brake'
            True
          )
          Controller'
          Controller'suspended'
        )
      )
    )
  )
  "

definition VC3 where
  "VC3 inv0 env s0 user'value pressure'value \<equiv>
  (
    (
      (
        (inv0
          s0
        )
      \<and>
        (env
          (setVarBool
            (setVarBool
              s0
              user'
              user'value
            )
            pressure'
            pressure'value
          )
        )
      )
    \<and>
      (
        (
          (
            (getPstate
              (setVarBool
                (setVarBool
                  s0
                  user'
                  user'value
                )
                pressure'
                pressure'value
              )
              Controller'
            )
          =
            Controller'motionless'
          )
        \<and>
          (getVarBool
            (setVarBool
              (setVarBool
                s0
                user'
                user'value
              )
              pressure'
              pressure'value
            )
            user'
          )
        )
      \<and>
        (\<not>
          (getVarBool
            (setVarBool
              (setVarBool
                s0
                user'
                user'value
              )
              pressure'
              pressure'value
            )
            pressure'
          )
        )
      )
    )
  -->
    (inv0
      (toEnv
        (setPstate
          (setVarBool
            (setVarBool
              (setVarBool
                s0
                user'
                user'value
              )
              pressure'
              pressure'value
            )
            rotation'
            True
          )
          Controller'
          Controller'rotating'
        )
      )
    )
  )
  "

definition VC4 where
  "VC4 inv0 env s0 user'value pressure'value \<equiv>
  (
    (
      (
        (inv0
          s0
        )
      \<and>
        (env
          (setVarBool
            (setVarBool
              s0
              user'
              user'value
            )
            pressure'
            pressure'value
          )
        )
      )
    \<and>
      (
        (
          (getPstate
            (setVarBool
              (setVarBool
                s0
                user'
                user'value
              )
              pressure'
              pressure'value
            )
            Controller'
          )
        =
          Controller'motionless'
        )
      \<and>
        (\<not>
          (getVarBool
            (setVarBool
              (setVarBool
                s0
                user'
                user'value
              )
              pressure'
              pressure'value
            )
            user'
          )
        )
      )
    )
  -->
    (inv0
      (toEnv
        (setVarBool
          (setVarBool
            s0
            user'
            user'value
          )
          pressure'
          pressure'value
        )
      )
    )
  )
  "

definition VC5 where
  "VC5 inv0 env s0 user'value pressure'value \<equiv>
  (
    (
      (
        (inv0
          s0
        )
      \<and>
        (env
          (setVarBool
            (setVarBool
              s0
              user'
              user'value
            )
            pressure'
            pressure'value
          )
        )
      )
    \<and>
      (
        (
          (
            (getPstate
              (setVarBool
                (setVarBool
                  s0
                  user'
                  user'value
                )
                pressure'
                pressure'value
              )
              Controller'
            )
          =
            Controller'rotating'
          )
        \<and>
          (getVarBool
            (setVarBool
              (setVarBool
                s0
                user'
                user'value
              )
              pressure'
              pressure'value
            )
            pressure'
          )
        )
      \<and>
        (
          DELAY'TIMEOUT
        <=
          (ltime
            (setPstate
              (setVarBool
                (setVarBool
                  (setVarBool
                    (setVarBool
                      s0
                      user'
                      user'value
                    )
                    pressure'
                    pressure'value
                  )
                  rotation'
                  False
                )
                brake'
                True
              )
              Controller'
              Controller'suspended'
            )
            Controller'
          )
        )
      )
    )
  -->
    (inv0
      (toEnv
        (setPstate
          (setVarBool
            (setPstate
              (setVarBool
                (setVarBool
                  (setVarBool
                    (setVarBool
                      s0
                      user'
                      user'value
                    )
                    pressure'
                    pressure'value
                  )
                  rotation'
                  False
                )
                brake'
                True
              )
              Controller'
              Controller'suspended'
            )
            rotation'
            False
          )
          Controller'
          Controller'motionless'
        )
      )
    )
  )
  "

definition VC6 where
  "VC6 inv0 env s0 user'value pressure'value \<equiv>
  (
    (
      (
        (inv0
          s0
        )
      \<and>
        (env
          (setVarBool
            (setVarBool
              s0
              user'
              user'value
            )
            pressure'
            pressure'value
          )
        )
      )
    \<and>
      (
        (
          (
            (getPstate
              (setVarBool
                (setVarBool
                  s0
                  user'
                  user'value
                )
                pressure'
                pressure'value
              )
              Controller'
            )
          =
            Controller'rotating'
          )
        \<and>
          (getVarBool
            (setVarBool
              (setVarBool
                s0
                user'
                user'value
              )
              pressure'
              pressure'value
            )
            pressure'
          )
        )
      \<and>
        (\<not>
          (
            DELAY'TIMEOUT
          <=
            (ltime
              (setPstate
                (setVarBool
                  (setVarBool
                    (setVarBool
                      (setVarBool
                        s0
                        user'
                        user'value
                      )
                      pressure'
                      pressure'value
                    )
                    rotation'
                    False
                  )
                  brake'
                  True
                )
                Controller'
                Controller'suspended'
              )
              Controller'
            )
          )
        )
      )
    )
  -->
    (inv0
      (toEnv
        (setPstate
          (setVarBool
            (setVarBool
              (setVarBool
                (setVarBool
                  s0
                  user'
                  user'value
                )
                pressure'
                pressure'value
              )
              rotation'
              False
            )
            brake'
            True
          )
          Controller'
          Controller'suspended'
        )
      )
    )
  )
  "

definition VC7 where
  "VC7 inv0 env s0 user'value pressure'value \<equiv>
  (
    (
      (
        (inv0
          s0
        )
      \<and>
        (env
          (setVarBool
            (setVarBool
              s0
              user'
              user'value
            )
            pressure'
            pressure'value
          )
        )
      )
    \<and>
      (
        (
          (
            (
              (getPstate
                (setVarBool
                  (setVarBool
                    s0
                    user'
                    user'value
                  )
                  pressure'
                  pressure'value
                )
                Controller'
              )
            =
              Controller'rotating'
            )
          \<and>
            (\<not>
              (getVarBool
                (setVarBool
                  (setVarBool
                    s0
                    user'
                    user'value
                  )
                  pressure'
                  pressure'value
                )
                pressure'
              )
            )
          )
        \<and>
          (getVarBool
            (setVarBool
              (setVarBool
                s0
                user'
                user'value
              )
              pressure'
              pressure'value
            )
            user'
          )
        )
      \<and>
        (
          DELAY'TIMEOUT
        <=
          (ltime
            (reset
              (setVarBool
                (setVarBool
                  s0
                  user'
                  user'value
                )
                pressure'
                pressure'value
              )
              Controller'
            )
            Controller'
          )
        )
      )
    )
  -->
    (inv0
      (toEnv
        (setPstate
          (setVarBool
            (reset
              (setVarBool
                (setVarBool
                  s0
                  user'
                  user'value
                )
                pressure'
                pressure'value
              )
              Controller'
            )
            rotation'
            False
          )
          Controller'
          Controller'motionless'
        )
      )
    )
  )
  "

definition VC8 where
  "VC8 inv0 env s0 user'value pressure'value \<equiv>
  (
    (
      (
        (inv0
          s0
        )
      \<and>
        (env
          (setVarBool
            (setVarBool
              s0
              user'
              user'value
            )
            pressure'
            pressure'value
          )
        )
      )
    \<and>
      (
        (
          (
            (
              (getPstate
                (setVarBool
                  (setVarBool
                    s0
                    user'
                    user'value
                  )
                  pressure'
                  pressure'value
                )
                Controller'
              )
            =
              Controller'rotating'
            )
          \<and>
            (\<not>
              (getVarBool
                (setVarBool
                  (setVarBool
                    s0
                    user'
                    user'value
                  )
                  pressure'
                  pressure'value
                )
                pressure'
              )
            )
          )
        \<and>
          (getVarBool
            (setVarBool
              (setVarBool
                s0
                user'
                user'value
              )
              pressure'
              pressure'value
            )
            user'
          )
        )
      \<and>
        (\<not>
          (
            DELAY'TIMEOUT
          <=
            (ltime
              (reset
                (setVarBool
                  (setVarBool
                    s0
                    user'
                    user'value
                  )
                  pressure'
                  pressure'value
                )
                Controller'
              )
              Controller'
            )
          )
        )
      )
    )
  -->
    (inv0
      (toEnv
        (reset
          (setVarBool
            (setVarBool
              s0
              user'
              user'value
            )
            pressure'
            pressure'value
          )
          Controller'
        )
      )
    )
  )
  "

definition VC9 where
  "VC9 inv0 env s0 user'value pressure'value \<equiv>
  (
    (
      (
        (inv0
          s0
        )
      \<and>
        (env
          (setVarBool
            (setVarBool
              s0
              user'
              user'value
            )
            pressure'
            pressure'value
          )
        )
      )
    \<and>
      (
        (
          (
            (
              (getPstate
                (setVarBool
                  (setVarBool
                    s0
                    user'
                    user'value
                  )
                  pressure'
                  pressure'value
                )
                Controller'
              )
            =
              Controller'rotating'
            )
          \<and>
            (\<not>
              (getVarBool
                (setVarBool
                  (setVarBool
                    s0
                    user'
                    user'value
                  )
                  pressure'
                  pressure'value
                )
                pressure'
              )
            )
          )
        \<and>
          (\<not>
            (getVarBool
              (setVarBool
                (setVarBool
                  s0
                  user'
                  user'value
                )
                pressure'
                pressure'value
              )
              user'
            )
          )
        )
      \<and>
        (
          DELAY'TIMEOUT
        <=
          (ltime
            (setVarBool
              (setVarBool
                s0
                user'
                user'value
              )
              pressure'
              pressure'value
            )
            Controller'
          )
        )
      )
    )
  -->
    (inv0
      (toEnv
        (setPstate
          (setVarBool
            (setVarBool
              (setVarBool
                s0
                user'
                user'value
              )
              pressure'
              pressure'value
            )
            rotation'
            False
          )
          Controller'
          Controller'motionless'
        )
      )
    )
  )
  "

definition VC10 where
  "VC10 inv0 env s0 user'value pressure'value \<equiv>
  (
    (
      (
        (inv0
          s0
        )
      \<and>
        (env
          (setVarBool
            (setVarBool
              s0
              user'
              user'value
            )
            pressure'
            pressure'value
          )
        )
      )
    \<and>
      (
        (
          (
            (
              (getPstate
                (setVarBool
                  (setVarBool
                    s0
                    user'
                    user'value
                  )
                  pressure'
                  pressure'value
                )
                Controller'
              )
            =
              Controller'rotating'
            )
          \<and>
            (\<not>
              (getVarBool
                (setVarBool
                  (setVarBool
                    s0
                    user'
                    user'value
                  )
                  pressure'
                  pressure'value
                )
                pressure'
              )
            )
          )
        \<and>
          (\<not>
            (getVarBool
              (setVarBool
                (setVarBool
                  s0
                  user'
                  user'value
                )
                pressure'
                pressure'value
              )
              user'
            )
          )
        )
      \<and>
        (\<not>
          (
            DELAY'TIMEOUT
          <=
            (ltime
              (setVarBool
                (setVarBool
                  s0
                  user'
                  user'value
                )
                pressure'
                pressure'value
              )
              Controller'
            )
          )
        )
      )
    )
  -->
    (inv0
      (toEnv
        (setVarBool
          (setVarBool
            s0
            user'
            user'value
          )
          pressure'
          pressure'value
        )
      )
    )
  )
  "

definition VC11 where
  "VC11 inv0 env s0 user'value pressure'value \<equiv>
  (
    (
      (
        (inv0
          s0
        )
      \<and>
        (env
          (setVarBool
            (setVarBool
              s0
              user'
              user'value
            )
            pressure'
            pressure'value
          )
        )
      )
    \<and>
      (
        (
          (
            (getPstate
              (setVarBool
                (setVarBool
                  s0
                  user'
                  user'value
                )
                pressure'
                pressure'value
              )
              Controller'
            )
          =
            Controller'suspended'
          )
        \<and>
          (getVarBool
            (setVarBool
              (setVarBool
                s0
                user'
                user'value
              )
              pressure'
              pressure'value
            )
            pressure'
          )
        )
      \<and>
        (
          SUSPENSION_TIME'TIMEOUT
        <=
          (ltime
            (reset
              (setVarBool
                (setVarBool
                  s0
                  user'
                  user'value
                )
                pressure'
                pressure'value
              )
              Controller'
            )
            Controller'
          )
        )
      )
    )
  -->
    (inv0
      (toEnv
        (setPstate
          (setVarBool
            (setVarBool
              (reset
                (setVarBool
                  (setVarBool
                    s0
                    user'
                    user'value
                  )
                  pressure'
                  pressure'value
                )
                Controller'
              )
              brake'
              False
            )
            rotation'
            True
          )
          Controller'
          Controller'rotating'
        )
      )
    )
  )
  "

definition VC12 where
  "VC12 inv0 env s0 user'value pressure'value \<equiv>
  (
    (
      (
        (inv0
          s0
        )
      \<and>
        (env
          (setVarBool
            (setVarBool
              s0
              user'
              user'value
            )
            pressure'
            pressure'value
          )
        )
      )
    \<and>
      (
        (
          (
            (getPstate
              (setVarBool
                (setVarBool
                  s0
                  user'
                  user'value
                )
                pressure'
                pressure'value
              )
              Controller'
            )
          =
            Controller'suspended'
          )
        \<and>
          (getVarBool
            (setVarBool
              (setVarBool
                s0
                user'
                user'value
              )
              pressure'
              pressure'value
            )
            pressure'
          )
        )
      \<and>
        (\<not>
          (
            SUSPENSION_TIME'TIMEOUT
          <=
            (ltime
              (reset
                (setVarBool
                  (setVarBool
                    s0
                    user'
                    user'value
                  )
                  pressure'
                  pressure'value
                )
                Controller'
              )
              Controller'
            )
          )
        )
      )
    )
  -->
    (inv0
      (toEnv
        (reset
          (setVarBool
            (setVarBool
              s0
              user'
              user'value
            )
            pressure'
            pressure'value
          )
          Controller'
        )
      )
    )
  )
  "

definition VC13 where
  "VC13 inv0 env s0 user'value pressure'value \<equiv>
  (
    (
      (
        (inv0
          s0
        )
      \<and>
        (env
          (setVarBool
            (setVarBool
              s0
              user'
              user'value
            )
            pressure'
            pressure'value
          )
        )
      )
    \<and>
      (
        (
          (
            (getPstate
              (setVarBool
                (setVarBool
                  s0
                  user'
                  user'value
                )
                pressure'
                pressure'value
              )
              Controller'
            )
          =
            Controller'suspended'
          )
        \<and>
          (\<not>
            (getVarBool
              (setVarBool
                (setVarBool
                  s0
                  user'
                  user'value
                )
                pressure'
                pressure'value
              )
              pressure'
            )
          )
        )
      \<and>
        (
          SUSPENSION_TIME'TIMEOUT
        <=
          (ltime
            (setVarBool
              (setVarBool
                s0
                user'
                user'value
              )
              pressure'
              pressure'value
            )
            Controller'
          )
        )
      )
    )
  -->
    (inv0
      (toEnv
        (setPstate
          (setVarBool
            (setVarBool
              (setVarBool
                (setVarBool
                  s0
                  user'
                  user'value
                )
                pressure'
                pressure'value
              )
              brake'
              False
            )
            rotation'
            True
          )
          Controller'
          Controller'rotating'
        )
      )
    )
  )
  "

definition VC14 where
  "VC14 inv0 env s0 user'value pressure'value \<equiv>
  (
    (
      (
        (inv0
          s0
        )
      \<and>
        (env
          (setVarBool
            (setVarBool
              s0
              user'
              user'value
            )
            pressure'
            pressure'value
          )
        )
      )
    \<and>
      (
        (
          (
            (getPstate
              (setVarBool
                (setVarBool
                  s0
                  user'
                  user'value
                )
                pressure'
                pressure'value
              )
              Controller'
            )
          =
            Controller'suspended'
          )
        \<and>
          (\<not>
            (getVarBool
              (setVarBool
                (setVarBool
                  s0
                  user'
                  user'value
                )
                pressure'
                pressure'value
              )
              pressure'
            )
          )
        )
      \<and>
        (\<not>
          (
            SUSPENSION_TIME'TIMEOUT
          <=
            (ltime
              (setVarBool
                (setVarBool
                  s0
                  user'
                  user'value
                )
                pressure'
                pressure'value
              )
              Controller'
            )
          )
        )
      )
    )
  -->
    (inv0
      (toEnv
        (setVarBool
          (setVarBool
            s0
            user'
            user'value
          )
          pressure'
          pressure'value
        )
      )
    )
  )
  "

definition VC15 where
  "VC15 inv0 env s0 user'value pressure'value \<equiv>
  (
    (
      (
        (inv0
          s0
        )
      \<and>
        (env
          (setVarBool
            (setVarBool
              s0
              user'
              user'value
            )
            pressure'
            pressure'value
          )
        )
      )
    \<and>
      (
        (getPstate
          (setVarBool
            (setVarBool
              s0
              user'
              user'value
            )
            pressure'
            pressure'value
          )
          Controller'
        )
      =
        STOP
      )
    )
  -->
    (inv0
      (toEnv
        (setVarBool
          (setVarBool
            s0
            user'
            user'value
          )
          pressure'
          pressure'value
        )
      )
    )
  )
  "

definition VC16 where
  "VC16 inv0 env s0 user'value pressure'value \<equiv>
  (
    (
      (
        (inv0
          s0
        )
      \<and>
        (env
          (setVarBool
            (setVarBool
              s0
              user'
              user'value
            )
            pressure'
            pressure'value
          )
        )
      )
    \<and>
      (
        (getPstate
          (setVarBool
            (setVarBool
              s0
              user'
              user'value
            )
            pressure'
            pressure'value
          )
          Controller'
        )
      =
        ERROR
      )
    )
  -->
    (inv0
      (toEnv
        (setVarBool
          (setVarBool
            s0
            user'
            user'value
          )
          pressure'
          pressure'value
        )
      )
    )
  )
  "
end
