theory GasSeparator imports VCProving.VCTheory
begin

abbreviation v_AutoBtn' :: variable where "v_AutoBtn' \<equiv> (Suc 0)"
abbreviation v_ManualBtn' :: variable where "v_ManualBtn' \<equiv> (Suc (Suc 0))"
abbreviation v_SafetyStopBtn' :: variable where "v_SafetyStopBtn' \<equiv> (Suc (Suc (Suc 0)))"
abbreviation v_EmergencyBtn' :: variable where "v_EmergencyBtn' \<equiv> (Suc (Suc (Suc (Suc 0))))"
abbreviation v_ThighAbnormally' :: variable where "v_ThighAbnormally' \<equiv> (Suc (Suc (Suc (Suc (Suc 0)))))"
abbreviation v_Thigh' :: variable where "v_Thigh' \<equiv> (Suc (Suc (Suc (Suc (Suc (Suc 0))))))"
abbreviation v_Tlow' :: variable where "v_Tlow' \<equiv> (Suc (Suc (Suc (Suc (Suc (Suc (Suc 0)))))))"
abbreviation v_PhighAbnormally' :: variable where "v_PhighAbnormally' \<equiv> (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc 0))))))))"
abbreviation v_Phigh' :: variable where "v_Phigh' \<equiv> (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc 0)))))))))"
abbreviation v_Plow' :: variable where "v_Plow' \<equiv> (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc 0))))))))))"
abbreviation v_Lfull' :: variable where "v_Lfull' \<equiv> (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc 0)))))))))))"
abbreviation v_Ldeg' :: variable where "v_Ldeg' \<equiv> (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc 0))))))))))))"
abbreviation v_Llow' :: variable where "v_Llow' \<equiv> (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc 0)))))))))))))"
abbreviation v_Lempty' :: variable where "v_Lempty' \<equiv> (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc 0))))))))))))))"
abbreviation v_filling' :: variable where "v_filling' \<equiv> (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc 0)))))))))))))))"
abbreviation v_release' :: variable where "v_release' \<equiv> (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc 0))))))))))))))))"
abbreviation v_inert' :: variable where "v_inert' \<equiv> (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc 0)))))))))))))))))"
abbreviation v_purge' :: variable where "v_purge' \<equiv> (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc 0))))))))))))))))))"
abbreviation v_emptying' :: variable where "v_emptying' \<equiv> (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc 0)))))))))))))))))))"
abbreviation v_heater' :: variable where "v_heater' \<equiv> (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc 0))))))))))))))))))))"
abbreviation v_AutoLED' :: variable where "v_AutoLED' \<equiv> (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc 0)))))))))))))))))))))"
abbreviation v_ManualLED' :: variable where "v_ManualLED' \<equiv> (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc 0))))))))))))))))))))))"
abbreviation v_SafetyLED' :: variable where "v_SafetyLED' \<equiv> (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc 0)))))))))))))))))))))))"
abbreviation v_EmergencyLED' :: variable where "v_EmergencyLED' \<equiv> (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc 0))))))))))))))))))))))))"
abbreviation v_FillingLED' :: variable where "v_FillingLED' \<equiv> (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc 0)))))))))))))))))))))))))"
abbreviation v_DegasLED' :: variable where "v_DegasLED' \<equiv> (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc 0))))))))))))))))))))))))))"
abbreviation v_EmptyingLED' :: variable where "v_EmptyingLED' \<equiv> (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc 0)))))))))))))))))))))))))))"
abbreviation v_HeatingLED' :: variable where "v_HeatingLED' \<equiv> (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc 0))))))))))))))))))))))))))))"
abbreviation v_GasAccumulatingLED' :: variable where "v_GasAccumulatingLED' \<equiv> (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc 0)))))))))))))))))))))))))))))"
abbreviation v_ReleasingLED' :: variable where "v_ReleasingLED' \<equiv> (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc 0))))))))))))))))))))))))))))))"
abbreviation v_LfullLED' :: variable where "v_LfullLED' \<equiv> (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc 0)))))))))))))))))))))))))))))))"
abbreviation v_LdegLED' :: variable where "v_LdegLED' \<equiv> (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc 0))))))))))))))))))))))))))))))))"
abbreviation v_LlowLED' :: variable where "v_LlowLED' \<equiv> (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc 0)))))))))))))))))))))))))))))))))"
abbreviation v_LemptyLED' :: variable where "v_LemptyLED' \<equiv> (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc 0))))))))))))))))))))))))))))))))))"
abbreviation v_ThighLED' :: variable where "v_ThighLED' \<equiv> (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc 0)))))))))))))))))))))))))))))))))))"
abbreviation v_TlowLED' :: variable where "v_TlowLED' \<equiv> (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc 0))))))))))))))))))))))))))))))))))))"
abbreviation v_PhighLED' :: variable where "v_PhighLED' \<equiv> (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc 0)))))))))))))))))))))))))))))))))))))"
abbreviation v_PlowLED' :: variable where "v_PlowLED' \<equiv> (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc 0))))))))))))))))))))))))))))))))))))))"

abbreviation p_EmergencyControl' :: process where "p_EmergencyControl' \<equiv> (Suc (Suc 0))"
abbreviation p_AutoModeControl' :: process where "p_AutoModeControl' \<equiv> (Suc (Suc (Suc 0)))"
abbreviation p_ButtonPressControl' :: process where "p_ButtonPressControl' \<equiv> (Suc 0)"
abbreviation p_DegassingControl' :: process where "p_DegassingControl' \<equiv> (Suc (Suc (Suc (Suc 0))))"

abbreviation p_EmergencyControl's_emptying' :: pstate where "p_EmergencyControl's_emptying' \<equiv> (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc 0))))))))"
abbreviation p_EmergencyControl's_purge' :: pstate where "p_EmergencyControl's_purge' \<equiv> (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc 0)))))))))"
abbreviation p_EmergencyControl's_autoMode' :: pstate where "p_EmergencyControl's_autoMode' \<equiv> (Suc (Suc (Suc (Suc (Suc (Suc (Suc 0)))))))"
abbreviation p_AutoModeControl's_filling' :: pstate where "p_AutoModeControl's_filling' \<equiv> (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc 0))))))))))"
abbreviation p_AutoModeControl's_emptying' :: pstate where "p_AutoModeControl's_emptying' \<equiv> (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc 0))))))))))))"
abbreviation p_AutoModeControl's_degassing' :: pstate where "p_AutoModeControl's_degassing' \<equiv> (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc 0)))))))))))"
abbreviation p_ButtonPressControl's_waiting' :: pstate where "p_ButtonPressControl's_waiting' \<equiv> (Suc (Suc 0))"
abbreviation p_ButtonPressControl's_waitingForStageCompletion' :: pstate where "p_ButtonPressControl's_waitingForStageCompletion' \<equiv> (Suc (Suc (Suc (Suc (Suc (Suc 0))))))"
abbreviation p_ButtonPressControl's_waitingForEmptying' :: pstate where "p_ButtonPressControl's_waitingForEmptying' \<equiv> (Suc (Suc (Suc (Suc 0))))"
abbreviation p_ButtonPressControl's_purge' :: pstate where "p_ButtonPressControl's_purge' \<equiv> (Suc (Suc (Suc (Suc (Suc 0)))))"
abbreviation p_ButtonPressControl's_autoMode' :: pstate where "p_ButtonPressControl's_autoMode' \<equiv> (Suc (Suc (Suc 0)))"
abbreviation p_DegassingControl's_releasing' :: pstate where "p_DegassingControl's_releasing' \<equiv> (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc 0)))))))))))))))"
abbreviation p_DegassingControl's_heating' :: pstate where "p_DegassingControl's_heating' \<equiv> (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc 0)))))))))))))"
abbreviation p_DegassingControl's_accumulating' :: pstate where "p_DegassingControl's_accumulating' \<equiv> (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc (Suc 0))))))))))))))"

abbreviation v_PRESSED' :: bool where "v_PRESSED' \<equiv> True"
abbreviation v_TURN_ON' :: bool where "v_TURN_ON' \<equiv> True"
abbreviation v_TURN_OFF' :: bool where "v_TURN_OFF' \<equiv> False"
abbreviation v_DEGASSING_TIMEOUT' :: nat where "v_DEGASSING_TIMEOUT' \<equiv> 60000"
abbreviation v_HEATING_TIMEOUT' :: nat where "v_HEATING_TIMEOUT' \<equiv> 10000"
abbreviation v_ACCUMULATING_TIMEOUT' :: nat where "v_ACCUMULATING_TIMEOUT' \<equiv> 10000"
abbreviation v_RELEASE_TIMEOUT' :: nat where "v_RELEASE_TIMEOUT' \<equiv> 10000"
abbreviation v_PURGE_TIMEOUT' :: nat where "v_PURGE_TIMEOUT' \<equiv> 10000"

abbreviation v_DEGASSING_TIMEOUT'TIMEOUT :: nat where "v_DEGASSING_TIMEOUT'TIMEOUT \<equiv> 600"
abbreviation v_HEATING_TIMEOUT'TIMEOUT :: nat where "v_HEATING_TIMEOUT'TIMEOUT \<equiv> 100"
abbreviation v_ACCUMULATING_TIMEOUT'TIMEOUT :: nat where "v_ACCUMULATING_TIMEOUT'TIMEOUT \<equiv> 100"
abbreviation v_RELEASE_TIMEOUT'TIMEOUT :: nat where "v_RELEASE_TIMEOUT'TIMEOUT \<equiv> 100"
abbreviation v_PURGE_TIMEOUT'TIMEOUT :: nat where "v_PURGE_TIMEOUT'TIMEOUT \<equiv> 100"

end

