/**
 * generated by Xtext 2.36.0
 */
package su.nsk.iae.rpl.rPL.impl;

import org.eclipse.emf.ecore.EClass;

import su.nsk.iae.rpl.invpatterngenerator.LemmaPremise;
import su.nsk.iae.rpl.invpatterngenerator.LemmaPremiseInstanceCreator;
import su.nsk.iae.rpl.invpatterngenerator.ParameterValueMap;
import su.nsk.iae.rpl.rPL.ConjunctionLemmaPremiseFormula;
import su.nsk.iae.rpl.rPL.RPLPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Conjunction Lemma Premise Formula</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class ConjunctionLemmaPremiseFormulaImpl extends DisjunctionLemmaPremiseFormulaImpl implements ConjunctionLemmaPremiseFormula
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ConjunctionLemmaPremiseFormulaImpl()
  {
    super();
  }

  @Override
public LemmaPremise substitiuteParams(LemmaPremiseInstanceCreator instCreator, ParameterValueMap params) {
	return instCreator.substituteParams(this, params);
}

/**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return RPLPackage.Literals.CONJUNCTION_LEMMA_PREMISE_FORMULA;
  }

} //ConjunctionLemmaPremiseFormulaImpl
