/**
 * generated by Xtext 2.36.0
 */
package su.nsk.iae.rpl.rPL.impl;

import org.eclipse.emf.ecore.EClass;

import su.nsk.iae.rpl.rPL.ConjunctionPatternFreeFormula;
import su.nsk.iae.rpl.rPL.RPLPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Conjunction Pattern Free Formula</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class ConjunctionPatternFreeFormulaImpl extends PatternFreeFormulaImpl implements ConjunctionPatternFreeFormula
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ConjunctionPatternFreeFormulaImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return RPLPackage.Literals.CONJUNCTION_PATTERN_FREE_FORMULA;
  }

} //ConjunctionPatternFreeFormulaImpl
