/**
 * generated by Xtext 2.36.0
 */
package su.nsk.iae.rpl.rPL.impl;

import org.eclipse.emf.ecore.EClass;

import su.nsk.iae.rpl.invpatterngenerator.OuterFormulaGenerator;
import su.nsk.iae.rpl.invpatterngenerator.OuterExtraInvariantFormula;
import su.nsk.iae.rpl.rPL.ConjunctionFormula;
import su.nsk.iae.rpl.rPL.RPLPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Conjunction Formula</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class ConjunctionFormulaImpl extends FormulaImpl implements ConjunctionFormula
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ConjunctionFormulaImpl()
  {
    super();
  }

  @Override
public <T> T generateFormula(OuterFormulaGenerator<T> generator) {

	return generator.generateFormula(this);
}

/**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return RPLPackage.Literals.CONJUNCTION_FORMULA;
  }

} //ConjunctionFormulaImpl
