/**
 * generated by Xtext 2.36.0
 */
package su.nsk.iae.rpl.rPL.impl;

import org.eclipse.emf.ecore.EClass;

import su.nsk.iae.rpl.rPL.DisjunctionLemmaPremiseFormula;
import su.nsk.iae.rpl.rPL.RPLPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Disjunction Lemma Premise Formula</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class DisjunctionLemmaPremiseFormulaImpl extends LemmaPremiseFormulaImpl implements DisjunctionLemmaPremiseFormula
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected DisjunctionLemmaPremiseFormulaImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return RPLPackage.Literals.DISJUNCTION_LEMMA_PREMISE_FORMULA;
  }

} //DisjunctionLemmaPremiseFormulaImpl
