/**
 * generated by Xtext 2.36.0
 */
package su.nsk.iae.rpl.rPL.impl;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import su.nsk.iae.rpl.rPL.FunApplication;
import su.nsk.iae.rpl.rPL.FunctionalParameter;
import su.nsk.iae.rpl.rPL.RPLPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Fun Application</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link su.nsk.iae.rpl.rPL.impl.FunApplicationImpl#getFnParam <em>Fn Param</em>}</li>
 * </ul>
 *
 * @generated
 */
public class FunApplicationImpl extends PrimaryTermImpl implements FunApplication
{
  /**
   * The cached value of the '{@link #getFnParam() <em>Fn Param</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getFnParam()
   * @generated
   * @ordered
   */
  protected FunctionalParameter fnParam;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected FunApplicationImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return RPLPackage.Literals.FUN_APPLICATION;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public FunctionalParameter getFnParam()
  {
    if (fnParam != null && fnParam.eIsProxy())
    {
      InternalEObject oldFnParam = (InternalEObject)fnParam;
      fnParam = (FunctionalParameter)eResolveProxy(oldFnParam);
      if (fnParam != oldFnParam)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, RPLPackage.FUN_APPLICATION__FN_PARAM, oldFnParam, fnParam));
      }
    }
    return fnParam;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public FunctionalParameter basicGetFnParam()
  {
    return fnParam;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setFnParam(FunctionalParameter newFnParam)
  {
    FunctionalParameter oldFnParam = fnParam;
    fnParam = newFnParam;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, RPLPackage.FUN_APPLICATION__FN_PARAM, oldFnParam, fnParam));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case RPLPackage.FUN_APPLICATION__FN_PARAM:
        if (resolve) return getFnParam();
        return basicGetFnParam();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case RPLPackage.FUN_APPLICATION__FN_PARAM:
        setFnParam((FunctionalParameter)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case RPLPackage.FUN_APPLICATION__FN_PARAM:
        setFnParam((FunctionalParameter)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case RPLPackage.FUN_APPLICATION__FN_PARAM:
        return fnParam != null;
    }
    return super.eIsSet(featureID);
  }

} //FunApplicationImpl
