/**
 * generated by Xtext 2.36.0
 */
package su.nsk.iae.rpl.rPL.impl;

import org.eclipse.emf.ecore.EClass;

import su.nsk.iae.rpl.invpatterngenerator.Term;
import su.nsk.iae.rpl.invpatterngenerator.TermConverter;
import su.nsk.iae.rpl.rPL.NegationTerm;
import su.nsk.iae.rpl.rPL.RPLPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Negation Term</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class NegationTermImpl extends ConjunctionTermImpl implements NegationTerm
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected NegationTermImpl()
  {
    super();
  }

  @Override
public Term convert(TermConverter converter) {
	return converter.convertTerm(this);
}

/**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return RPLPackage.Literals.NEGATION_TERM;
  }

} //NegationTermImpl
