/**
 * generated by Xtext 2.36.0
 */
package su.nsk.iae.rpl.rPL.impl;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import su.nsk.iae.rpl.rPL.OuterRequirementPattern;
import su.nsk.iae.rpl.rPL.RPLPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Outer Requirement Pattern</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class OuterRequirementPatternImpl extends MinimalEObjectImpl.Container implements OuterRequirementPattern
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected OuterRequirementPatternImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return RPLPackage.Literals.OUTER_REQUIREMENT_PATTERN;
  }

} //OuterRequirementPatternImpl
