/**
 * generated by Xtext 2.36.0
 */
package su.nsk.iae.rpl.rPL.impl;

import java.util.Collection;
import java.util.List;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

import su.nsk.iae.rpl.invpatterngenerator.ExtraInvariantPatternGenerator;
import su.nsk.iae.rpl.invpatterngenerator.Formula;
import su.nsk.iae.rpl.invpatterngenerator.FormulaParameterValue;
import su.nsk.iae.rpl.rPL.ConstantParameter;
import su.nsk.iae.rpl.rPL.FormulaParameter;
import su.nsk.iae.rpl.rPL.PastExtraInvariantPattern;
import su.nsk.iae.rpl.rPL.PastLemmas;
import su.nsk.iae.rpl.rPL.PastRequirementPattern;
import su.nsk.iae.rpl.rPL.RPLPackage;
import su.nsk.iae.rpl.rPL.Term;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Past Requirement Pattern</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link su.nsk.iae.rpl.rPL.impl.PastRequirementPatternImpl#getName <em>Name</em>}</li>
 *   <li>{@link su.nsk.iae.rpl.rPL.impl.PastRequirementPatternImpl#getCParams <em>CParams</em>}</li>
 *   <li>{@link su.nsk.iae.rpl.rPL.impl.PastRequirementPatternImpl#getFmParams <em>Fm Params</em>}</li>
 *   <li>{@link su.nsk.iae.rpl.rPL.impl.PastRequirementPatternImpl#getFile <em>File</em>}</li>
 *   <li>{@link su.nsk.iae.rpl.rPL.impl.PastRequirementPatternImpl#getExtraInvPattern <em>Extra Inv Pattern</em>}</li>
 *   <li>{@link su.nsk.iae.rpl.rPL.impl.PastRequirementPatternImpl#getLemmas <em>Lemmas</em>}</li>
 * </ul>
 *
 * @generated
 */
public class PastRequirementPatternImpl extends ElementImpl implements PastRequirementPattern
{
  /**
   * The default value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected static final String NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected String name = NAME_EDEFAULT;

  /**
   * The cached value of the '{@link #getCParams() <em>CParams</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCParams()
   * @generated
   * @ordered
   */
  protected EList<ConstantParameter> cParams;

  /**
   * The cached value of the '{@link #getFmParams() <em>Fm Params</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getFmParams()
   * @generated
   * @ordered
   */
  protected EList<FormulaParameter> fmParams;

  /**
   * The default value of the '{@link #getFile() <em>File</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getFile()
   * @generated
   * @ordered
   */
  protected static final String FILE_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getFile() <em>File</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getFile()
   * @generated
   * @ordered
   */
  protected String file = FILE_EDEFAULT;

  /**
   * The cached value of the '{@link #getExtraInvPattern() <em>Extra Inv Pattern</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getExtraInvPattern()
   * @generated
   * @ordered
   */
  protected PastExtraInvariantPattern extraInvPattern;

  /**
   * The cached value of the '{@link #getLemmas() <em>Lemmas</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getLemmas()
   * @generated
   * @ordered
   */
  protected PastLemmas lemmas;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected PastRequirementPatternImpl()
  {
    super();
  }
  
  @Override
  public Formula generateExtraInvariantPatternInstance(List<Term> cParams, List<FormulaParameterValue> einvFmParams,
  		ExtraInvariantPatternGenerator generator) {
  	return generator.generatePatternInstance()
  			getExtraInvPattern(),
  			cParams,
  			einvFmParams);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return RPLPackage.Literals.PAST_REQUIREMENT_PATTERN;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setName(String newName)
  {
    String oldName = name;
    name = newName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, RPLPackage.PAST_REQUIREMENT_PATTERN__NAME, oldName, name));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<ConstantParameter> getCParams()
  {
    if (cParams == null)
    {
      cParams = new EObjectContainmentEList<ConstantParameter>(ConstantParameter.class, this, RPLPackage.PAST_REQUIREMENT_PATTERN__CPARAMS);
    }
    return cParams;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<FormulaParameter> getFmParams()
  {
    if (fmParams == null)
    {
      fmParams = new EObjectContainmentEList<FormulaParameter>(FormulaParameter.class, this, RPLPackage.PAST_REQUIREMENT_PATTERN__FM_PARAMS);
    }
    return fmParams;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getFile()
  {
    return file;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setFile(String newFile)
  {
    String oldFile = file;
    file = newFile;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, RPLPackage.PAST_REQUIREMENT_PATTERN__FILE, oldFile, file));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public PastExtraInvariantPattern getExtraInvPattern()
  {
    if (extraInvPattern != null && extraInvPattern.eIsProxy())
    {
      InternalEObject oldExtraInvPattern = (InternalEObject)extraInvPattern;
      extraInvPattern = (PastExtraInvariantPattern)eResolveProxy(oldExtraInvPattern);
      if (extraInvPattern != oldExtraInvPattern)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, RPLPackage.PAST_REQUIREMENT_PATTERN__EXTRA_INV_PATTERN, oldExtraInvPattern, extraInvPattern));
      }
    }
    return extraInvPattern;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public PastExtraInvariantPattern basicGetExtraInvPattern()
  {
    return extraInvPattern;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setExtraInvPattern(PastExtraInvariantPattern newExtraInvPattern)
  {
    PastExtraInvariantPattern oldExtraInvPattern = extraInvPattern;
    extraInvPattern = newExtraInvPattern;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, RPLPackage.PAST_REQUIREMENT_PATTERN__EXTRA_INV_PATTERN, oldExtraInvPattern, extraInvPattern));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public PastLemmas getLemmas()
  {
    return lemmas;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetLemmas(PastLemmas newLemmas, NotificationChain msgs)
  {
    PastLemmas oldLemmas = lemmas;
    lemmas = newLemmas;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, RPLPackage.PAST_REQUIREMENT_PATTERN__LEMMAS, oldLemmas, newLemmas);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setLemmas(PastLemmas newLemmas)
  {
    if (newLemmas != lemmas)
    {
      NotificationChain msgs = null;
      if (lemmas != null)
        msgs = ((InternalEObject)lemmas).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - RPLPackage.PAST_REQUIREMENT_PATTERN__LEMMAS, null, msgs);
      if (newLemmas != null)
        msgs = ((InternalEObject)newLemmas).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - RPLPackage.PAST_REQUIREMENT_PATTERN__LEMMAS, null, msgs);
      msgs = basicSetLemmas(newLemmas, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, RPLPackage.PAST_REQUIREMENT_PATTERN__LEMMAS, newLemmas, newLemmas));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case RPLPackage.PAST_REQUIREMENT_PATTERN__CPARAMS:
        return ((InternalEList<?>)getCParams()).basicRemove(otherEnd, msgs);
      case RPLPackage.PAST_REQUIREMENT_PATTERN__FM_PARAMS:
        return ((InternalEList<?>)getFmParams()).basicRemove(otherEnd, msgs);
      case RPLPackage.PAST_REQUIREMENT_PATTERN__LEMMAS:
        return basicSetLemmas(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case RPLPackage.PAST_REQUIREMENT_PATTERN__NAME:
        return getName();
      case RPLPackage.PAST_REQUIREMENT_PATTERN__CPARAMS:
        return getCParams();
      case RPLPackage.PAST_REQUIREMENT_PATTERN__FM_PARAMS:
        return getFmParams();
      case RPLPackage.PAST_REQUIREMENT_PATTERN__FILE:
        return getFile();
      case RPLPackage.PAST_REQUIREMENT_PATTERN__EXTRA_INV_PATTERN:
        if (resolve) return getExtraInvPattern();
        return basicGetExtraInvPattern();
      case RPLPackage.PAST_REQUIREMENT_PATTERN__LEMMAS:
        return getLemmas();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case RPLPackage.PAST_REQUIREMENT_PATTERN__NAME:
        setName((String)newValue);
        return;
      case RPLPackage.PAST_REQUIREMENT_PATTERN__CPARAMS:
        getCParams().clear();
        getCParams().addAll((Collection<? extends ConstantParameter>)newValue);
        return;
      case RPLPackage.PAST_REQUIREMENT_PATTERN__FM_PARAMS:
        getFmParams().clear();
        getFmParams().addAll((Collection<? extends FormulaParameter>)newValue);
        return;
      case RPLPackage.PAST_REQUIREMENT_PATTERN__FILE:
        setFile((String)newValue);
        return;
      case RPLPackage.PAST_REQUIREMENT_PATTERN__EXTRA_INV_PATTERN:
        setExtraInvPattern((PastExtraInvariantPattern)newValue);
        return;
      case RPLPackage.PAST_REQUIREMENT_PATTERN__LEMMAS:
        setLemmas((PastLemmas)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case RPLPackage.PAST_REQUIREMENT_PATTERN__NAME:
        setName(NAME_EDEFAULT);
        return;
      case RPLPackage.PAST_REQUIREMENT_PATTERN__CPARAMS:
        getCParams().clear();
        return;
      case RPLPackage.PAST_REQUIREMENT_PATTERN__FM_PARAMS:
        getFmParams().clear();
        return;
      case RPLPackage.PAST_REQUIREMENT_PATTERN__FILE:
        setFile(FILE_EDEFAULT);
        return;
      case RPLPackage.PAST_REQUIREMENT_PATTERN__EXTRA_INV_PATTERN:
        setExtraInvPattern((PastExtraInvariantPattern)null);
        return;
      case RPLPackage.PAST_REQUIREMENT_PATTERN__LEMMAS:
        setLemmas((PastLemmas)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case RPLPackage.PAST_REQUIREMENT_PATTERN__NAME:
        return NAME_EDEFAULT == null ? name != null : !NAME_EDEFAULT.equals(name);
      case RPLPackage.PAST_REQUIREMENT_PATTERN__CPARAMS:
        return cParams != null && !cParams.isEmpty();
      case RPLPackage.PAST_REQUIREMENT_PATTERN__FM_PARAMS:
        return fmParams != null && !fmParams.isEmpty();
      case RPLPackage.PAST_REQUIREMENT_PATTERN__FILE:
        return FILE_EDEFAULT == null ? file != null : !FILE_EDEFAULT.equals(file);
      case RPLPackage.PAST_REQUIREMENT_PATTERN__EXTRA_INV_PATTERN:
        return extraInvPattern != null;
      case RPLPackage.PAST_REQUIREMENT_PATTERN__LEMMAS:
        return lemmas != null;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (name: ");
    result.append(name);
    result.append(", file: ");
    result.append(file);
    result.append(')');
    return result.toString();
  }

} //PastRequirementPatternImpl
