/**
 * generated by Xtext 2.36.0
 */
package su.nsk.iae.rpl.rPL.impl;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import su.nsk.iae.rpl.rPL.PrimaryTerm;
import su.nsk.iae.rpl.rPL.RPLPackage;
import su.nsk.iae.rpl.rPL.Term;
import su.nsk.iae.rpl.rPL.UpdateStateVariable;
import su.nsk.iae.rpl.rPL.Variable;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Primary Term</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link su.nsk.iae.rpl.rPL.impl.PrimaryTermImpl#getVariable <em>Variable</em>}</li>
 *   <li>{@link su.nsk.iae.rpl.rPL.impl.PrimaryTermImpl#getState <em>State</em>}</li>
 *   <li>{@link su.nsk.iae.rpl.rPL.impl.PrimaryTermImpl#getNestedTerm <em>Nested Term</em>}</li>
 * </ul>
 *
 * @generated
 */
public class PrimaryTermImpl extends UnaryTermImpl implements PrimaryTerm
{
  /**
   * The cached value of the '{@link #getVariable() <em>Variable</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getVariable()
   * @generated
   * @ordered
   */
  protected Variable variable;

  /**
   * The cached value of the '{@link #getState() <em>State</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getState()
   * @generated
   * @ordered
   */
  protected UpdateStateVariable state;

  /**
   * The cached value of the '{@link #getNestedTerm() <em>Nested Term</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getNestedTerm()
   * @generated
   * @ordered
   */
  protected Term nestedTerm;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected PrimaryTermImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return RPLPackage.Literals.PRIMARY_TERM;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Variable getVariable()
  {
    if (variable != null && variable.eIsProxy())
    {
      InternalEObject oldVariable = (InternalEObject)variable;
      variable = (Variable)eResolveProxy(oldVariable);
      if (variable != oldVariable)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, RPLPackage.PRIMARY_TERM__VARIABLE, oldVariable, variable));
      }
    }
    return variable;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Variable basicGetVariable()
  {
    return variable;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setVariable(Variable newVariable)
  {
    Variable oldVariable = variable;
    variable = newVariable;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, RPLPackage.PRIMARY_TERM__VARIABLE, oldVariable, variable));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public UpdateStateVariable getState()
  {
    if (state != null && state.eIsProxy())
    {
      InternalEObject oldState = (InternalEObject)state;
      state = (UpdateStateVariable)eResolveProxy(oldState);
      if (state != oldState)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, RPLPackage.PRIMARY_TERM__STATE, oldState, state));
      }
    }
    return state;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public UpdateStateVariable basicGetState()
  {
    return state;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setState(UpdateStateVariable newState)
  {
    UpdateStateVariable oldState = state;
    state = newState;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, RPLPackage.PRIMARY_TERM__STATE, oldState, state));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Term getNestedTerm()
  {
    return nestedTerm;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetNestedTerm(Term newNestedTerm, NotificationChain msgs)
  {
    Term oldNestedTerm = nestedTerm;
    nestedTerm = newNestedTerm;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, RPLPackage.PRIMARY_TERM__NESTED_TERM, oldNestedTerm, newNestedTerm);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setNestedTerm(Term newNestedTerm)
  {
    if (newNestedTerm != nestedTerm)
    {
      NotificationChain msgs = null;
      if (nestedTerm != null)
        msgs = ((InternalEObject)nestedTerm).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - RPLPackage.PRIMARY_TERM__NESTED_TERM, null, msgs);
      if (newNestedTerm != null)
        msgs = ((InternalEObject)newNestedTerm).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - RPLPackage.PRIMARY_TERM__NESTED_TERM, null, msgs);
      msgs = basicSetNestedTerm(newNestedTerm, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, RPLPackage.PRIMARY_TERM__NESTED_TERM, newNestedTerm, newNestedTerm));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case RPLPackage.PRIMARY_TERM__NESTED_TERM:
        return basicSetNestedTerm(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case RPLPackage.PRIMARY_TERM__VARIABLE:
        if (resolve) return getVariable();
        return basicGetVariable();
      case RPLPackage.PRIMARY_TERM__STATE:
        if (resolve) return getState();
        return basicGetState();
      case RPLPackage.PRIMARY_TERM__NESTED_TERM:
        return getNestedTerm();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case RPLPackage.PRIMARY_TERM__VARIABLE:
        setVariable((Variable)newValue);
        return;
      case RPLPackage.PRIMARY_TERM__STATE:
        setState((UpdateStateVariable)newValue);
        return;
      case RPLPackage.PRIMARY_TERM__NESTED_TERM:
        setNestedTerm((Term)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case RPLPackage.PRIMARY_TERM__VARIABLE:
        setVariable((Variable)null);
        return;
      case RPLPackage.PRIMARY_TERM__STATE:
        setState((UpdateStateVariable)null);
        return;
      case RPLPackage.PRIMARY_TERM__NESTED_TERM:
        setNestedTerm((Term)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case RPLPackage.PRIMARY_TERM__VARIABLE:
        return variable != null;
      case RPLPackage.PRIMARY_TERM__STATE:
        return state != null;
      case RPLPackage.PRIMARY_TERM__NESTED_TERM:
        return nestedTerm != null;
    }
    return super.eIsSet(featureID);
  }

} //PrimaryTermImpl
