/**
 * generated by Xtext 2.36.0
 */
package su.nsk.iae.rpl.rPL.impl;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import su.nsk.iae.rpl.invpatterngenerator.InnerExtraInvariantFormula;
import su.nsk.iae.rpl.invpatterngenerator.InnerFormulaGenerator;
import su.nsk.iae.rpl.invpatterngenerator.PatternFreeInnerFormula;
import su.nsk.iae.rpl.rPL.NegationFormula;
import su.nsk.iae.rpl.rPL.PatternFreeFormula;
import su.nsk.iae.rpl.rPL.PrimaryPatternFreeFormula;
import su.nsk.iae.rpl.rPL.RPLPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Primary Pattern Free Formula</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link su.nsk.iae.rpl.rPL.impl.PrimaryPatternFreeFormulaImpl#getAtomic <em>Atomic</em>}</li>
 *   <li>{@link su.nsk.iae.rpl.rPL.impl.PrimaryPatternFreeFormulaImpl#getNestedFormula <em>Nested Formula</em>}</li>
 * </ul>
 *
 * @generated
 */
public class PrimaryPatternFreeFormulaImpl extends ConjunctionPatternFreeFormulaImpl implements PrimaryPatternFreeFormula
{
  /**
   * The cached value of the '{@link #getAtomic() <em>Atomic</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getAtomic()
   * @generated
   * @ordered
   */
  protected NegationFormula atomic;

  /**
   * The cached value of the '{@link #getNestedFormula() <em>Nested Formula</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getNestedFormula()
   * @generated
   * @ordered
   */
  protected PatternFreeFormula nestedFormula;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected PrimaryPatternFreeFormulaImpl()
  {
    super();
  }

  @Override
public PatternFreeInnerFormula generateFormula(InnerFormulaGenerator<?> generator) {
	return generator.generatePatternFreeFormula(this);
}

/**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return RPLPackage.Literals.PRIMARY_PATTERN_FREE_FORMULA;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NegationFormula getAtomic()
  {
    return atomic;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetAtomic(NegationFormula newAtomic, NotificationChain msgs)
  {
    NegationFormula oldAtomic = atomic;
    atomic = newAtomic;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, RPLPackage.PRIMARY_PATTERN_FREE_FORMULA__ATOMIC, oldAtomic, newAtomic);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setAtomic(NegationFormula newAtomic)
  {
    if (newAtomic != atomic)
    {
      NotificationChain msgs = null;
      if (atomic != null)
        msgs = ((InternalEObject)atomic).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - RPLPackage.PRIMARY_PATTERN_FREE_FORMULA__ATOMIC, null, msgs);
      if (newAtomic != null)
        msgs = ((InternalEObject)newAtomic).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - RPLPackage.PRIMARY_PATTERN_FREE_FORMULA__ATOMIC, null, msgs);
      msgs = basicSetAtomic(newAtomic, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, RPLPackage.PRIMARY_PATTERN_FREE_FORMULA__ATOMIC, newAtomic, newAtomic));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public PatternFreeFormula getNestedFormula()
  {
    return nestedFormula;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetNestedFormula(PatternFreeFormula newNestedFormula, NotificationChain msgs)
  {
    PatternFreeFormula oldNestedFormula = nestedFormula;
    nestedFormula = newNestedFormula;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, RPLPackage.PRIMARY_PATTERN_FREE_FORMULA__NESTED_FORMULA, oldNestedFormula, newNestedFormula);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setNestedFormula(PatternFreeFormula newNestedFormula)
  {
    if (newNestedFormula != nestedFormula)
    {
      NotificationChain msgs = null;
      if (nestedFormula != null)
        msgs = ((InternalEObject)nestedFormula).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - RPLPackage.PRIMARY_PATTERN_FREE_FORMULA__NESTED_FORMULA, null, msgs);
      if (newNestedFormula != null)
        msgs = ((InternalEObject)newNestedFormula).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - RPLPackage.PRIMARY_PATTERN_FREE_FORMULA__NESTED_FORMULA, null, msgs);
      msgs = basicSetNestedFormula(newNestedFormula, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, RPLPackage.PRIMARY_PATTERN_FREE_FORMULA__NESTED_FORMULA, newNestedFormula, newNestedFormula));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case RPLPackage.PRIMARY_PATTERN_FREE_FORMULA__ATOMIC:
        return basicSetAtomic(null, msgs);
      case RPLPackage.PRIMARY_PATTERN_FREE_FORMULA__NESTED_FORMULA:
        return basicSetNestedFormula(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case RPLPackage.PRIMARY_PATTERN_FREE_FORMULA__ATOMIC:
        return getAtomic();
      case RPLPackage.PRIMARY_PATTERN_FREE_FORMULA__NESTED_FORMULA:
        return getNestedFormula();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case RPLPackage.PRIMARY_PATTERN_FREE_FORMULA__ATOMIC:
        setAtomic((NegationFormula)newValue);
        return;
      case RPLPackage.PRIMARY_PATTERN_FREE_FORMULA__NESTED_FORMULA:
        setNestedFormula((PatternFreeFormula)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case RPLPackage.PRIMARY_PATTERN_FREE_FORMULA__ATOMIC:
        setAtomic((NegationFormula)null);
        return;
      case RPLPackage.PRIMARY_PATTERN_FREE_FORMULA__NESTED_FORMULA:
        setNestedFormula((PatternFreeFormula)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case RPLPackage.PRIMARY_PATTERN_FREE_FORMULA__ATOMIC:
        return atomic != null;
      case RPLPackage.PRIMARY_PATTERN_FREE_FORMULA__NESTED_FORMULA:
        return nestedFormula != null;
    }
    return super.eIsSet(featureID);
  }

} //PrimaryPatternFreeFormulaImpl
