/**
 * generated by Xtext 2.36.0
 */
package su.nsk.iae.rpl.rPL.impl;

import org.eclipse.emf.ecore.EClass;

import su.nsk.iae.rpl.rPL.ProgramVariable;
import su.nsk.iae.rpl.rPL.RPLPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Program Variable</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class ProgramVariableImpl extends VariableImpl implements ProgramVariable
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ProgramVariableImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return RPLPackage.Literals.PROGRAM_VARIABLE;
  }

} //ProgramVariableImpl
