/**
 * generated by Xtext 2.36.0
 */
package su.nsk.iae.rpl.rPL.impl;

import org.eclipse.emf.ecore.EClass;

import su.nsk.iae.rpl.rPL.RPLPackage;
import su.nsk.iae.rpl.rPL.RegularFormulaParameter;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Regular Formula Parameter</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class RegularFormulaParameterImpl extends FormulaParameterImpl implements RegularFormulaParameter
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected RegularFormulaParameterImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return RPLPackage.Literals.REGULAR_FORMULA_PARAMETER;
  }

} //RegularFormulaParameterImpl
